// <auto-generated />
using System;
using Learnexia.Modules.Parent.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Learnexia.Modules.Parent.Infrastructure.Migrations
{
    [DbContext(typeof(ParentDbContext))]
    [Migration("20260524130240_InitialParent")]
    partial class InitialParent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("parent")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Learnexia.Modules.Parent.Domain.Entities.ParentStudent", b =>
                {
                    b.Property<int>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()")
                        .HasComment("UTC timestamp when the parent-student link was created");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasComment("Id of the user who created the link (plain int, no FK constraint)");

                    b.HasKey("ParentId", "StudentId");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("IX_ParentStudent_StudentId");

                    b.ToTable("ParentStudent", "parent");
                });
#pragma warning restore 612, 618
        }
    }
}
