"""BL-03-PY-4-contract — Testcontainers Postgres proof of the INFER_EDGES
claim/advance contract (mirrors ``tests/test_ingest_contract.py`` for the third lane).

Proves, against a real Postgres mirroring the shipped EF schema:
  1. The infer poller claims ONLY ``JobType='infer_edges'`` rows (Pending parse +
     ingest jobs are left untouched — lane isolation across all three lanes).
  2. The claim is atomic (Pending -> Processing) and concurrency-safe.
  3. The Done write-back carries the FROZEN ``{inference_model, edges}`` ResultJson
     the .NET EdgeInferenceAdvanceService reads (exact snake_case keys + PascalCase
     relationship_type), with Status + CompletedAt set.
  4. A Failed infer job writes the diagnostics shape the .NET side reads, and the
     worker does NOT touch RetryCount (that is .NET's policy).

Everything runs with the LLM MOCKED (the deterministic MockEdgeInferer).
Skipped automatically when Docker is unavailable (sandboxed runner).
"""

from __future__ import annotations

import json

import pytest

from curriculum_intelligence.app.config import (
    InferenceConfig,
    InfererBackendKind,
    InferPollerConfig,
    Settings,
)
from curriculum_intelligence.app.db import (
    JOB_TYPE_INFER_EDGES,
    JOB_TYPE_INGEST,
    JOB_TYPE_PARSE,
    STATUS_DONE,
    STATUS_FAILED,
    STATUS_PENDING,
    STATUS_PROCESSING,
    PipelineJobRepository,
)

pytestmark = pytest.mark.contract

psycopg = pytest.importorskip("psycopg")

try:
    from testcontainers.postgres import PostgresContainer
except Exception:  # pragma: no cover - dep missing
    PostgresContainer = None  # type: ignore[assignment]


SCHEMA = "curriculum"

_DDL = f"""
CREATE SCHEMA IF NOT EXISTS "{SCHEMA}";
CREATE TABLE IF NOT EXISTS "{SCHEMA}"."PipelineJobs" (
    "Id"            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "JobType"       varchar(64)  NOT NULL,
    "Status"        varchar(32)  NOT NULL DEFAULT 'Pending',
    "DocumentId"    integer      NOT NULL,
    "PayloadJson"   text         NOT NULL,
    "ResultJson"    text         NULL,
    "ErrorMessage"  varchar(2048) NULL,
    "ClaimedAt"     timestamptz  NULL,
    "CompletedAt"   timestamptz  NULL,
    "RetryCount"    integer      NOT NULL DEFAULT 0,
    "CreatedAt"     timestamp    NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_pipeline_jobs_status_job_type
    ON "{SCHEMA}"."PipelineJobs" ("Status", "JobType");
"""

_DIVISION = "math.grade4.numbers.long-division"
_FRACTIONS = "math.grade4.fractions.add-fractions"
_DECIMALS = "math.grade4.decimals.add-decimals"

_INFER_PAYLOAD = {
    "document_id": 7,
    "nodes": [
        {
            "skill_key": _DIVISION,
            "title": "long division",
            "node_type": "Skill",
            "subject_code": "math",
            "grade": 4,
            "difficulty": 2,
        },
        {
            "skill_key": _FRACTIONS,
            "title": "add fractions",
            "node_type": "Skill",
            "subject_code": "math",
            "grade": 4,
            "difficulty": 3,
        },
        {
            "skill_key": _DECIMALS,
            "title": "add decimals",
            "node_type": "Skill",
            "subject_code": "math",
            "grade": 4,
            "difficulty": 4,
        },
    ],
}
_PARSE_PAYLOAD = {"object_key": "x.pdf", "content_type": "application/pdf"}
_INGEST_PAYLOAD = {"artifact_key": "artifacts/x.json", "document_id": 7}


@pytest.fixture(scope="module")
def pg_dsn():
    if PostgresContainer is None:
        pytest.skip("testcontainers not installed")
    try:
        container = PostgresContainer("postgres:15-alpine", driver=None)
        container.start()
    except Exception as exc:  # pragma: no cover - no docker
        pytest.skip(f"Docker not available for Testcontainers: {exc}")
    try:
        dsn = container.get_connection_url()
        with psycopg.connect(dsn, autocommit=True) as conn:
            conn.execute(_DDL)
        yield dsn
    finally:
        container.stop()


def _seed_job(dsn: str, *, job_type: str, payload: dict, document_id: int = 7) -> int:
    with psycopg.connect(dsn, autocommit=True) as conn:
        row = conn.execute(
            f'''INSERT INTO "{SCHEMA}"."PipelineJobs" ("JobType","Status","DocumentId","PayloadJson")
                VALUES (%s, %s, %s, %s) RETURNING "Id"''',
            (job_type, STATUS_PENDING, document_id, json.dumps(payload)),
        ).fetchone()
        return row[0]


def _status(dsn: str, job_id: int) -> dict:
    from psycopg.rows import dict_row

    with psycopg.connect(dsn, autocommit=True) as conn:
        with conn.cursor(row_factory=dict_row) as cur:
            cur.execute(f'SELECT * FROM "{SCHEMA}"."PipelineJobs" WHERE "Id" = %s', (job_id,))
            return cur.fetchone()


def _settings(dsn: str) -> Settings:
    from curriculum_intelligence.app.config import DatabaseConfig

    return Settings(
        database=DatabaseConfig(dsn=dsn, schema=SCHEMA),
        infer_poller=InferPollerConfig(interval_seconds=0.1, job_type=JOB_TYPE_INFER_EDGES),
        inference=InferenceConfig(inferer_backend=InfererBackendKind.MOCK),
    )


def test_infer_poller_claims_only_infer_jobs(pg_dsn):
    from curriculum_intelligence.workers.infer_poller import InferPoller

    # Seed a parse + an ingest + an infer job — the infer poller must skip the others.
    parse_id = _seed_job(pg_dsn, job_type=JOB_TYPE_PARSE, payload=_PARSE_PAYLOAD)
    ingest_id = _seed_job(pg_dsn, job_type=JOB_TYPE_INGEST, payload=_INGEST_PAYLOAD)
    infer_id = _seed_job(pg_dsn, job_type=JOB_TYPE_INFER_EDGES, payload=_INFER_PAYLOAD)

    poller = InferPoller(_settings(pg_dsn))
    with psycopg.connect(pg_dsn, autocommit=False) as conn:
        handled = poller.poll_once(conn)
    assert handled is True

    assert _status(pg_dsn, infer_id)["Status"] == STATUS_DONE
    # the parse + ingest jobs were NOT touched by the infer lane
    assert _status(pg_dsn, parse_id)["Status"] == STATUS_PENDING
    assert _status(pg_dsn, ingest_id)["Status"] == STATUS_PENDING


def test_infer_claim_is_atomic(pg_dsn):
    job_id = _seed_job(pg_dsn, job_type=JOB_TYPE_INFER_EDGES, payload=_INFER_PAYLOAD)
    with psycopg.connect(pg_dsn, autocommit=False) as conn:
        repo = PipelineJobRepository(conn, schema=SCHEMA)
        job = repo.claim_next(JOB_TYPE_INFER_EDGES)
        assert job is not None and job.id == job_id
        assert job.status == STATUS_PROCESSING
    assert _status(pg_dsn, job_id)["ClaimedAt"] is not None


def test_infer_done_writeback_shape_matches_dotnet(pg_dsn):
    from curriculum_intelligence.workers.infer_poller import InferPoller

    job_id = _seed_job(pg_dsn, job_type=JOB_TYPE_INFER_EDGES, payload=_INFER_PAYLOAD)
    poller = InferPoller(_settings(pg_dsn))
    with psycopg.connect(pg_dsn, autocommit=False) as conn:
        assert poller.poll_once(conn) is True

    row = _status(pg_dsn, job_id)
    assert row["Status"] == STATUS_DONE
    assert row["CompletedAt"] is not None
    assert row["ErrorMessage"] is None
    parsed = json.loads(row["ResultJson"])
    # the EXACT frozen top-level keys the .NET EdgeInferenceAdvanceService reads
    assert set(parsed) >= {"inference_model", "edges"}
    assert parsed["inference_model"] == "lightrag-mock-v1"
    edge_keys = {(e["source_skill_key"], e["target_skill_key"]) for e in parsed["edges"]}
    assert (_DIVISION, _FRACTIONS) in edge_keys  # prereq chain emitted
    for e in parsed["edges"]:
        assert set(e) == {
            "source_skill_key",
            "target_skill_key",
            "relationship_type",
            "strength",
            "confidence",
        }
        assert e["relationship_type"] in {"Prerequisite", "Related"}
        assert 0.0 <= e["strength"] <= 1.0
        assert 0.0 <= e["confidence"] <= 1.0


def test_infer_failed_writeback_shape(pg_dsn):
    from curriculum_intelligence.workers.infer_poller import InferPoller

    # Empty node list -> terminal Failed with diagnostics.
    job_id = _seed_job(pg_dsn, job_type=JOB_TYPE_INFER_EDGES, payload={"document_id": 7, "nodes": []})
    poller = InferPoller(_settings(pg_dsn))
    with psycopg.connect(pg_dsn, autocommit=False) as conn:
        assert poller.poll_once(conn) is True

    row = _status(pg_dsn, job_id)
    assert row["Status"] == STATUS_FAILED
    assert row["ErrorMessage"] is not None
    assert row["CompletedAt"] is not None
    assert row["RetryCount"] == 0  # the worker never touches retry — .NET owns it
    diag = json.loads(row["ResultJson"])
    assert diag["infer_status"] == "failed"
