"""BL-05-PY-5-contract — Testcontainers Postgres proof of the INGEST claim/advance
contract (mirrors ``tests/test_outbox_contract.py`` for the ingest lane).

Proves, against a real Postgres mirroring the shipped EF schema:
  1. The ingest poller claims ONLY ``JobType='ingest'`` rows (a Pending parse job
     is left untouched — lane isolation).
  2. The claim is atomic (Pending -> Processing) and concurrency-safe.
  3. The Done write-back carries the ``{nodes, chunks, flags}`` ResultJson the
     .NET IngestJobAdvanceService reads, with Status + CompletedAt set.
  4. A Failed ingest job writes the diagnostics shape the .NET side reads, and the
     worker does NOT touch RetryCount (that is .NET's policy).

Skipped automatically when Docker is unavailable (sandboxed runner).
"""

from __future__ import annotations

import json

import pytest

from curriculum_intelligence.app.config import (
    AzureDocumentIntelligenceConfig,
    DatabaseConfig,
    IngestionConfig,
    IngestPollerConfig,
    ParserBackendKind,
    PollerConfig,
    Settings,
    StorageConfig,
)
from curriculum_intelligence.app.db import (
    JOB_TYPE_INGEST,
    JOB_TYPE_PARSE,
    STATUS_DONE,
    STATUS_FAILED,
    STATUS_PENDING,
    STATUS_PROCESSING,
    PipelineJobRepository,
)
from curriculum_intelligence.app.storage import InMemoryObjectStore

pytestmark = pytest.mark.contract

psycopg = pytest.importorskip("psycopg")

try:
    from testcontainers.postgres import PostgresContainer
except Exception:  # pragma: no cover - dep missing
    PostgresContainer = None  # type: ignore[assignment]


SCHEMA = "curriculum"

_DDL = f"""
CREATE SCHEMA IF NOT EXISTS "{SCHEMA}";
CREATE TABLE IF NOT EXISTS "{SCHEMA}"."PipelineJobs" (
    "Id"            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "JobType"       varchar(64)  NOT NULL,
    "Status"        varchar(32)  NOT NULL DEFAULT 'Pending',
    "DocumentId"    integer      NOT NULL,
    "PayloadJson"   text         NOT NULL,
    "ResultJson"    text         NULL,
    "ErrorMessage"  varchar(2048) NULL,
    "ClaimedAt"     timestamptz  NULL,
    "CompletedAt"   timestamptz  NULL,
    "RetryCount"    integer      NOT NULL DEFAULT 0,
    "CreatedAt"     timestamp    NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_pipeline_jobs_status_job_type
    ON "{SCHEMA}"."PipelineJobs" ("Status", "JobType");
"""

_ARTIFACT_KEY = "artifacts/g5-math.pdf.artifact.json"
_ARABIC = "اَلْكُسُورُ جُزْءٌ مِنَ الْكُلِّ. لِجَمْعِ الْكُسُورِ وَحِّدِ الْمَقَامَاتِ."

_INGEST_PAYLOAD = {"artifact_key": _ARTIFACT_KEY, "document_id": 7}
_PARSE_PAYLOAD = {"object_key": "x.pdf", "content_type": "application/pdf"}


def _artifact_bytes() -> bytes:
    artifact = {
        "document_id": 7,
        "schema_version": "1.0",
        "source_object_key": "g5-math.pdf",
        "content_type": "application/pdf",
        "chunks": [{"content_type": "text", "text": _ARABIC, "source_page": 3}],
        "__ingest_fixture__": {
            "nodes": [
                {
                    "node_type": "Unit",
                    "title": "اَلْكُسُورُ",
                    "grade": 5,
                    "subject_code": "math",
                    "language": "ar",
                    "slug_source": "fractions",
                    "unit_slug_source": "fractions",
                    "confidence": 0.95,
                    "parent_index": None,
                },
                {
                    "node_type": "Lesson",
                    "title": "جَمْعُ الْكُسُورِ",
                    "grade": 5,
                    "subject_code": "math",
                    "language": "ar",
                    "slug_source": "add-fractions",
                    "unit_slug_source": "fractions",
                    "confidence": 0.55,
                    "parent_index": 0,
                },
            ],
            "chunk_sources": [{"node_index": 1, "text": _ARABIC, "source_page": 3, "confidence": 0.5}],
        },
    }
    return json.dumps(artifact, ensure_ascii=False).encode("utf-8")


@pytest.fixture(scope="module")
def pg_dsn():
    if PostgresContainer is None:
        pytest.skip("testcontainers not installed")
    try:
        container = PostgresContainer("postgres:15-alpine", driver=None)
        container.start()
    except Exception as exc:  # pragma: no cover - no docker
        pytest.skip(f"Docker not available for Testcontainers: {exc}")
    try:
        dsn = container.get_connection_url()
        with psycopg.connect(dsn, autocommit=True) as conn:
            conn.execute(_DDL)
        yield dsn
    finally:
        container.stop()


def _seed_job(dsn: str, *, job_type: str, payload: dict, document_id: int = 7) -> int:
    with psycopg.connect(dsn, autocommit=True) as conn:
        row = conn.execute(
            f'''INSERT INTO "{SCHEMA}"."PipelineJobs" ("JobType","Status","DocumentId","PayloadJson")
                VALUES (%s, %s, %s, %s) RETURNING "Id"''',
            (job_type, STATUS_PENDING, document_id, json.dumps(payload)),
        ).fetchone()
        return row[0]


def _status(dsn: str, job_id: int) -> dict:
    from psycopg.rows import dict_row

    with psycopg.connect(dsn, autocommit=True) as conn:
        with conn.cursor(row_factory=dict_row) as cur:
            cur.execute(f'SELECT * FROM "{SCHEMA}"."PipelineJobs" WHERE "Id" = %s', (job_id,))
            return cur.fetchone()


def _settings(dsn: str, store: InMemoryObjectStore) -> Settings:
    return Settings(
        database=DatabaseConfig(dsn=dsn, schema=SCHEMA),
        storage=StorageConfig("minio:9000", "x", "y", "curriculum", False, "us-east-1"),
        azure_di=AzureDocumentIntelligenceConfig(endpoint=None, key=None),
        poller=PollerConfig(interval_seconds=0.1, job_type=JOB_TYPE_PARSE),
        ingest_poller=IngestPollerConfig(interval_seconds=0.1, job_type=JOB_TYPE_INGEST),
        ingestion=IngestionConfig(max_chunk_chars=40, confidence_threshold=0.7),
        parser_backend=ParserBackendKind.MOCK,
    )


def test_ingest_poller_claims_only_ingest_jobs(pg_dsn):
    from curriculum_intelligence.workers.ingest_poller import IngestPoller

    # Seed a parse job AND an ingest job — the ingest poller must skip the parse one.
    parse_id = _seed_job(pg_dsn, job_type=JOB_TYPE_PARSE, payload=_PARSE_PAYLOAD)
    ingest_id = _seed_job(pg_dsn, job_type=JOB_TYPE_INGEST, payload=_INGEST_PAYLOAD)

    store = InMemoryObjectStore()
    store.seed(_ARTIFACT_KEY, _artifact_bytes())
    poller = IngestPoller(_settings(pg_dsn, store), storage=store)

    with psycopg.connect(pg_dsn, autocommit=False) as conn:
        handled = poller.poll_once(conn)
    assert handled is True

    assert _status(pg_dsn, ingest_id)["Status"] == STATUS_DONE
    # the parse job was NOT touched by the ingest lane
    assert _status(pg_dsn, parse_id)["Status"] == STATUS_PENDING


def test_ingest_claim_is_atomic(pg_dsn):
    job_id = _seed_job(pg_dsn, job_type=JOB_TYPE_INGEST, payload=_INGEST_PAYLOAD)
    with psycopg.connect(pg_dsn, autocommit=False) as conn:
        repo = PipelineJobRepository(conn, schema=SCHEMA)
        job = repo.claim_next(JOB_TYPE_INGEST)
        assert job is not None and job.id == job_id
        assert job.status == STATUS_PROCESSING
    assert _status(pg_dsn, job_id)["ClaimedAt"] is not None


def test_ingest_done_writeback_shape_matches_dotnet(pg_dsn):
    from curriculum_intelligence.workers.ingest_poller import IngestPoller

    job_id = _seed_job(pg_dsn, job_type=JOB_TYPE_INGEST, payload=_INGEST_PAYLOAD)
    store = InMemoryObjectStore()
    store.seed(_ARTIFACT_KEY, _artifact_bytes())
    poller = IngestPoller(_settings(pg_dsn, store), storage=store)

    with psycopg.connect(pg_dsn, autocommit=False) as conn:
        assert poller.poll_once(conn) is True

    row = _status(pg_dsn, job_id)
    assert row["Status"] == STATUS_DONE
    assert row["CompletedAt"] is not None
    assert row["ErrorMessage"] is None
    parsed = json.loads(row["ResultJson"])
    # the exact top-level keys the .NET IngestJobAdvanceService reads
    assert set(parsed) >= {"nodes", "chunks", "flags"}
    assert parsed["nodes"][0]["skill_key"] == "math.grade5.fractions.fractions"
    assert parsed["nodes"][1]["confidence"] < 0.7  # emitted, not dropped
    assert any(f["kind"] == "low_confidence_node" for f in parsed["flags"])
    # tashkeel survived the DB round-trip (ResultJson stored as real chars)
    assert "\\u" not in row["ResultJson"]


def test_ingest_failed_writeback_shape(pg_dsn):
    from curriculum_intelligence.workers.ingest_poller import IngestPoller

    # Missing artifact in the store -> terminal Failed with diagnostics.
    job_id = _seed_job(
        pg_dsn, job_type=JOB_TYPE_INGEST, payload={"artifact_key": "artifacts/nope.json", "document_id": 7}
    )
    store = InMemoryObjectStore()  # empty
    poller = IngestPoller(_settings(pg_dsn, store), storage=store)

    with psycopg.connect(pg_dsn, autocommit=False) as conn:
        assert poller.poll_once(conn) is True

    row = _status(pg_dsn, job_id)
    assert row["Status"] == STATUS_FAILED
    assert row["ErrorMessage"] is not None
    assert row["CompletedAt"] is not None
    assert row["RetryCount"] == 0  # the worker never touches retry — .NET owns it
    diag = json.loads(row["ResultJson"])
    assert diag["ingest_status"] == "failed"
