"""PY-9-contract — Testcontainers Postgres proof of the atomic-claim contract.

Builds a minimal ``curriculum."PipelineJobs"`` table that mirrors the SHIPPED
.NET EF schema (PascalCase quoted columns, string Status/JobType), then proves:

  1. A Pending parse job is claimed exactly once (Pending -> Processing).
  2. Two CONCURRENT claim calls never grab the same job — the loser gets None.
  3. Done/Failed write-back produces exactly the shape the .NET advance service
     reads (Status string + ResultJson + CompletedAt; ErrorMessage on Failed).
  4. End-to-end through the poller with an in-memory store + mock parser.

Skipped automatically when Docker is unavailable (e.g. a sandboxed CI runner).
"""

from __future__ import annotations

import json
import threading

import pytest

from curriculum_intelligence.app.config import (
    AzureDocumentIntelligenceConfig,
    DatabaseConfig,
    ParserBackendKind,
    PollerConfig,
    Settings,
    StorageConfig,
)
from curriculum_intelligence.app.db import (
    STATUS_DONE,
    STATUS_FAILED,
    STATUS_PENDING,
    STATUS_PROCESSING,
    PipelineJobRepository,
)
from curriculum_intelligence.app.storage import InMemoryObjectStore

pytestmark = pytest.mark.contract

psycopg = pytest.importorskip("psycopg")

try:
    from testcontainers.postgres import PostgresContainer
except Exception:  # pragma: no cover - dep missing
    PostgresContainer = None  # type: ignore[assignment]


SCHEMA = "curriculum"

# Mirror of the shipped EF schema (the columns the contract depends on).
_DDL = f'''
CREATE SCHEMA IF NOT EXISTS "{SCHEMA}";
CREATE TABLE "{SCHEMA}"."PipelineJobs" (
    "Id"            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "JobType"       varchar(64)  NOT NULL,
    "Status"        varchar(32)  NOT NULL DEFAULT 'Pending',
    "DocumentId"    integer      NOT NULL,
    "PayloadJson"   text         NOT NULL,
    "ResultJson"    text         NULL,
    "ErrorMessage"  varchar(2048) NULL,
    "ClaimedAt"     timestamptz  NULL,
    "CompletedAt"   timestamptz  NULL,
    "RetryCount"    integer      NOT NULL DEFAULT 0,
    "CreatedAt"     timestamp    NOT NULL DEFAULT now()
);
CREATE INDEX ix_pipeline_jobs_status_job_type
    ON "{SCHEMA}"."PipelineJobs" ("Status", "JobType");
'''


@pytest.fixture(scope="module")
def pg_dsn():
    if PostgresContainer is None:
        pytest.skip("testcontainers not installed")
    try:
        container = PostgresContainer("postgres:15-alpine", driver=None)
        container.start()
    except Exception as exc:  # pragma: no cover - no docker
        pytest.skip(f"Docker not available for Testcontainers: {exc}")
    try:
        dsn = container.get_connection_url()  # postgresql://user:pass@host:port/db
        with psycopg.connect(dsn, autocommit=True) as conn:
            conn.execute(_DDL)
        yield dsn
    finally:
        container.stop()


def _seed_job(dsn: str, *, job_type: str = "parse", payload: dict | None = None) -> int:
    payload = payload or {"object_key": "abc-123.pdf", "content_type": "application/pdf"}
    with psycopg.connect(dsn, autocommit=True) as conn:
        row = conn.execute(
            f'''INSERT INTO "{SCHEMA}"."PipelineJobs" ("JobType","Status","DocumentId","PayloadJson")
                VALUES (%s, %s, %s, %s) RETURNING "Id"''',
            (job_type, STATUS_PENDING, 7, json.dumps(payload)),
        ).fetchone()
        return row[0]


def _status(dsn: str, job_id: int) -> dict:
    with psycopg.connect(dsn, autocommit=True) as conn:
        from psycopg.rows import dict_row

        with conn.cursor(row_factory=dict_row) as cur:
            cur.execute(f'SELECT * FROM "{SCHEMA}"."PipelineJobs" WHERE "Id" = %s', (job_id,))
            return cur.fetchone()


def test_single_claim_transitions_pending_to_processing(pg_dsn):
    job_id = _seed_job(pg_dsn)
    with psycopg.connect(pg_dsn, autocommit=False) as conn:
        repo = PipelineJobRepository(conn, schema=SCHEMA)
        job = repo.claim_next("parse")
        assert job is not None and job.id == job_id
        assert job.status == STATUS_PROCESSING

    row = _status(pg_dsn, job_id)
    assert row["Status"] == STATUS_PROCESSING
    assert row["ClaimedAt"] is not None


def test_concurrent_claims_never_double_grab(pg_dsn):
    job_id = _seed_job(pg_dsn)
    results: list = []
    barrier = threading.Barrier(2)

    def worker():
        # Each worker holds its own connection + open transaction simultaneously,
        # so the FOR UPDATE SKIP LOCKED race is genuinely exercised.
        conn = psycopg.connect(pg_dsn, autocommit=False)
        try:
            repo = PipelineJobRepository(conn, schema=SCHEMA)
            barrier.wait(timeout=10)
            results.append(repo.claim_next("parse"))
        finally:
            conn.close()

    t1 = threading.Thread(target=worker)
    t2 = threading.Thread(target=worker)
    t1.start()
    t2.start()
    t1.join()
    t2.join()

    claimed = [r for r in results if r is not None]
    missed = [r for r in results if r is None]
    assert len(claimed) == 1, f"exactly one worker must claim; got {results}"
    assert len(missed) == 1, "the other worker must get None (skipped the locked row)"
    assert claimed[0].id == job_id


def test_no_pending_job_returns_none(pg_dsn):
    with psycopg.connect(pg_dsn, autocommit=False) as conn:
        repo = PipelineJobRepository(conn, schema=SCHEMA)
        # drain any pending parse jobs first
        while repo.claim_next("parse") is not None:
            pass
        assert repo.claim_next("parse") is None


def test_done_writeback_shape(pg_dsn):
    job_id = _seed_job(pg_dsn)
    result_json = json.dumps(
        {"artifact_key": "artifacts/abc-123.pdf.artifact.json",
         "chapters": [{"number": 1, "title": "ch1", "page_start": 1, "page_end": 5}],
         "parse_status": "done", "diagnostics": None}
    )
    with psycopg.connect(pg_dsn, autocommit=False) as conn:
        repo = PipelineJobRepository(conn, schema=SCHEMA)
        repo.claim_next("parse")
        repo.mark_done(job_id, result_json)

    row = _status(pg_dsn, job_id)
    assert row["Status"] == STATUS_DONE
    assert row["CompletedAt"] is not None
    assert row["ErrorMessage"] is None
    parsed = json.loads(row["ResultJson"])
    # the exact keys the .NET advance service reads
    assert set(parsed) >= {"artifact_key", "chapters", "parse_status"}


def test_failed_writeback_shape(pg_dsn):
    job_id = _seed_job(pg_dsn)
    with psycopg.connect(pg_dsn, autocommit=False) as conn:
        repo = PipelineJobRepository(conn, schema=SCHEMA)
        repo.claim_next("parse")
        repo.mark_failed(job_id, "azure_di_analyze_failed: boom")

    row = _status(pg_dsn, job_id)
    assert row["Status"] == STATUS_FAILED
    assert row["ErrorMessage"].startswith("azure_di_analyze_failed")
    assert row["CompletedAt"] is not None
    # the worker did NOT touch RetryCount — that's .NET's job
    assert row["RetryCount"] == 0


def test_poller_end_to_end_with_mock(pg_dsn):
    from curriculum_intelligence.workers.poller import PipelinePoller

    job_id = _seed_job(pg_dsn)
    settings = Settings(
        database=DatabaseConfig(dsn=pg_dsn, schema=SCHEMA),
        storage=StorageConfig("minio:9000", "x", "y", "curriculum", False, "us-east-1"),
        azure_di=AzureDocumentIntelligenceConfig(endpoint=None, key=None),
        poller=PollerConfig(interval_seconds=0.1, job_type="parse"),
        parser_backend=ParserBackendKind.MOCK,
    )
    store = InMemoryObjectStore()
    store.seed("abc-123.pdf", b"%PDF-1.7 scanned arabic page")

    poller = PipelinePoller(settings, storage=store)
    with psycopg.connect(pg_dsn, autocommit=False) as conn:
        handled = poller.poll_once(conn)
    assert handled is True

    row = _status(pg_dsn, job_id)
    assert row["Status"] == STATUS_DONE
    inline = json.loads(row["ResultJson"])
    assert inline["parse_status"] == "done"
    # the artifact landed in the store under the derived key
    assert inline["artifact_key"] in store.keys
