<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Modules\Notifications\Learnexia.Modules.Notifications.Application\Learnexia.Modules.Notifications.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Notifications\Learnexia.Modules.Notifications.Domain\Learnexia.Modules.Notifications.Domain.csproj" />
  </ItemGroup>
</Project>
