using System.Security.Cryptography;
using System.Text;
using Pgvector;

namespace Learnexia.Modules.Curriculum.Infrastructure.Services;

/// <summary>
/// Deterministic placeholder embedding generator for the curriculum chunk seeder.
///
/// <para><strong>PURPOSE — PLACEHOLDER ONLY:</strong>
/// This helper produces L2-normalized 1024-dimensional vectors from text using a
/// SHA-256-seeded deterministic algorithm. It is NOT BGE-M3 and does NOT produce
/// semantically meaningful embeddings. Its sole purpose is to populate
/// <c>chunk_embeddings_bge_m3</c> rows during the dev/test seed phase so that the
/// vector-search mechanics (JOIN, filter, cosine <c>&lt;=&gt;</c>, HNSW index,
/// similarity floor, idempotency) can be fully validated without a live TEI endpoint.</para>
///
/// <para><strong>RE-EMBED REQUIRED:</strong>
/// Once the self-hosted BGE-M3 TEI endpoint (BE-0) is provisioned, ALL rows whose
/// <c>ModelVersion = "seed-placeholder-v0"</c> MUST be re-embedded with real BGE-M3.
/// The parity stamp makes the swap detectable: query the table for
/// <c>ModelVersion = 'seed-placeholder-v0'</c> and re-run ingestion against the live
/// TEI endpoint. The retrieval semantics will then be correct.</para>
///
/// <para><strong>Integration test usage:</strong>
/// <c>RagContextProviderTests</c> injects a stub <c>IEmbeddingProvider</c> that delegates
/// to <see cref="ComputeAsync"/> so the seeded vectors and the query vectors are
/// generated by the same deterministic function — guaranteeing that a seeded-skill query
/// returns a near-distance match and that an out-of-corpus text returns a larger distance
/// (below the similarity floor).</para>
/// </summary>
public static class DeterministicEmbedding
{
    public const int Dimension = 1024;

    /// <summary>Provider stamp written to <c>chunk_embeddings_bge_m3.Provider</c> for seeded rows.</summary>
    public const string PlaceholderProvider = "deterministic-placeholder";

    /// <summary>Model stamp written to <c>chunk_embeddings_bge_m3.Model</c> for seeded rows.</summary>
    public const string PlaceholderModel = "bge-m3";

    /// <summary>Version stamp written to <c>chunk_embeddings_bge_m3.ModelVersion</c> for seeded rows.
    /// Query for this value to find all rows that need re-embedding with real BGE-M3.</summary>
    public const string PlaceholderModelVersion = "seed-placeholder-v0";

    /// <summary>
    /// Produces a deterministic, L2-normalized <c>vector(1024)</c> from the given text.
    /// Two calls with the same input always return the same vector — making test assertions
    /// on similarity floor stable and reproducible.
    ///
    /// <para>Algorithm: divide 1024 dimensions into 32 blocks of 32 floats each. Each block
    /// is derived from <c>SHA-256("{blockIndex}:{text}")</c> — a distinct hash per block.
    /// Concatenate, then L2-normalize to the unit sphere. The per-block salting ensures that
    /// different texts produce nearly-orthogonal vectors (cosine distance ≈ 1.0), while the
    /// same text always produces cosine distance = 0. This property is required for the
    /// integration tests: same-text queries pass the similarity floor; out-of-corpus queries
    /// exceed it and return an empty list.</para>
    ///
    /// <para>The result is always on the unit sphere (consistent with BGE-M3 normalized output),
    /// so cosine distance is well-defined.</para>
    /// </summary>
    public static Task<Vector> ComputeAsync(string text, CancellationToken ct = default)
    {
        const int blocksCount  = 32;       // 32 blocks × 32 floats = 1024 dimensions
        const int floatsPerBlock = 32;

        var raw = new float[Dimension];

        // Each block uses a salted hash to ensure independence across dimensions.
        // Different texts → different hash bytes per block → near-orthogonal vectors.
        // Same text → identical hash bytes per block → identical vector (distance = 0).
        for (var block = 0; block < blocksCount; block++)
        {
            var saltedInput = Encoding.UTF8.GetBytes($"{block}:{text}");
            var hashBytes   = SHA256.HashData(saltedInput);

            for (var j = 0; j < floatsPerBlock; j++)
            {
                raw[block * floatsPerBlock + j] = hashBytes[j] / 128.0f - 1.0f;
            }
        }

        // L2-normalize so the vector sits on the unit sphere — required for valid cosine distances.
        var norm = MathF.Sqrt(raw.Sum(v => v * v));
        if (norm > 1e-8f)
        {
            for (var i = 0; i < Dimension; i++)
                raw[i] /= norm;
        }

        return Task.FromResult(new Vector(raw));
    }
}
