using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using FluentAssertions;
using Learnexia.Modules.Billing.Application.Abstractions;
using Learnexia.Modules.Billing.Domain.Entities;
using Learnexia.Modules.Billing.Domain.Enums;
using Learnexia.Modules.Billing.Infrastructure.Persistence;
using Learnexia.Modules.Billing.Infrastructure.Services;
using Learnexia.Shared.Contracts.Billing;
using Learnexia.Shared.Kernel.Abstractions;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Moq;
using Xunit;
#pragma warning disable CA1707

namespace Modules.Billing.UnitTests;

/// <summary>
/// Test-only <see cref="BillingDbContext"/> subclass that overrides the <c>xmin</c>
/// row-version mapping for <see cref="ChildEnergyAllocation"/> and <see cref="FamilyEnergyAccount"/>
/// so that EF can INSERT those rows in SQLite without failing on NOT NULL.
///
/// On Postgres, <c>xmin</c> is a system column generated by the DB on every write.
/// On SQLite (tests only), there is no such system column, so we must supply a default value.
/// This override applies <c>HasDefaultValue(1u)</c> for the SQLite schema only.
/// It has NO effect on the real Postgres schema or migrations.
/// </summary>
internal sealed class BillingTestDbContext : BillingDbContext
{
    public BillingTestDbContext(DbContextOptions<BillingDbContext> options) : base(options) { }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        // SQLite-only: supply a default of 1 for the xmin columns so EF INSERT works.
        // The column is normally generated by Postgres (server-side xmin); EF omits it from INSERTs.
        // SQLite has no such generator → NOT NULL fails unless a default is available.
        modelBuilder.Entity<ChildEnergyAllocation>()
            .Property(x => x.Version)
            .HasDefaultValue(1u);

        modelBuilder.Entity<FamilyEnergyAccount>()
            .Property(x => x.Version)
            .HasDefaultValue(1u);
    }
}

/// <summary>
/// Focused unit tests for P10-16 family allocation redistribution correctness.
///
/// All services run against SQLite in-memory (no Postgres required).
/// The real <see cref="BillingDbContext"/> is used with SQLite.
///
/// Note on seeding: <see cref="FamilyEnergyAccount"/> and <see cref="ChildEnergyAllocation"/>
/// both carry a <c>uint Version</c> mapped to the Postgres <c>xmin</c> system column as a
/// row-version concurrency token. SQLite does NOT auto-generate this column, so these two
/// entity types must be seeded via raw SQL (explicit <c>xmin=1</c>).
/// <see cref="Subscription"/> and <see cref="SeatReservation"/> have no <c>Version</c> column
/// and use standard EF Add + SaveChangesAsync.
///
/// Coverage:
///   AT-01  Cross-family rejection: fromChildId does not belong to this parent's wallet → Fail(ChildNotInFamily).
///   AT-02  Cross-family rejection: toChildId does not belong to this parent's wallet → Fail(ChildNotInFamily).
///   AT-03  Amount > source.Remaining → Fail(AmountExceedsRemaining).
///   AT-04  Amount = 0 → Fail(AmountExceedsRemaining).
///   AT-05  Only UNSPENT is movable: Allocated=100, Spent=60, Remaining=40;
///          transfer 41 → Fail; transfer 40 → Ok.
///   AT-06  Mid-cycle child with no allocation row: transfer to them
///          INSERTs a new ChildEnergyAllocation row and succeeds.
///   AT-07  Paired ledger rows: TransferOut (source) + TransferIn (destination)
///          share the same CorrelationId; both touch bucket A (Subscription) only.
///   AT-08  Idempotency: same IdempotencyKey twice does NOT double-move;
///          second call returns the prior result without appending new ledger rows.
///   AT-09  GetFamilyAllocationAsync: IsMidCycleNoGrant=true for a child with an active
///          seat but no current-cycle allocation row.
///   AT-10  GetFamilyAllocationAsync: all active-seat children appear, including zero-allocation ones.
/// </summary>
public sealed class FamilyAllocationTransferTests : IDisposable
{
    // ── SQLite fixtures ───────────────────────────────────────────────────────────────────────

    private readonly SqliteConnection _connection;
    private readonly BillingTestDbContext _db;
    private readonly Mock<ISeatStateQuery> _seatStateQueryMock;
    private readonly Mock<ICurrentUserService> _currentUserMock;

    public FamilyAllocationTransferTests()
    {
        _connection = new SqliteConnection("DataSource=:memory:");
        _connection.Open();

        var options = new DbContextOptionsBuilder<BillingDbContext>()
            .UseSqlite(_connection)
            .Options;

        _db = new BillingTestDbContext(options);
        _db.Database.EnsureCreated();

        _seatStateQueryMock = new Mock<ISeatStateQuery>();
        _currentUserMock    = new Mock<ICurrentUserService>();
        _currentUserMock.Setup(x => x.UserId).Returns(1);
    }

    public void Dispose()
    {
        _db.Dispose();
        _connection.Dispose();
    }

    private FamilyAllocationService BuildService()
    {
        var loggerMock = new Mock<ILoggerManager>();
        loggerMock.Setup(x => x.LogInfo(It.IsAny<string>()));
        loggerMock.Setup(x => x.LogError(It.IsAny<Exception>(), It.IsAny<string>()));
        return new FamilyAllocationService(_db, _seatStateQueryMock.Object, _currentUserMock.Object, loggerMock.Object);
    }

    // ── Seed helpers ──────────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Seeds a Subscription row using standard EF (no xmin column).
    /// Returns the created entity (with its generated Id).
    /// </summary>
    private async Task<Subscription> SeedSubscriptionAsync(int parentId = 1)
    {
        var sub = new Subscription
        {
            ParentUserId  = parentId,
            PlanCode      = PlanCode.Premium,
            Status        = SubscriptionStatus.Active,
            BillingPeriod = BillingPeriod.Monthly,
            CreatedAt     = DateTime.UtcNow.AddMonths(-1),
            CreatedBy     = 0,
        };
        _db.Subscriptions.Add(sub);
        await _db.SaveChangesAsync();
        return sub;
    }

    /// <summary>
    /// Seeds a FamilyEnergyAccount via raw SQL because the entity has uint Version mapped
    /// to the Postgres xmin system column — SQLite won't auto-generate it.
    /// Returns the generated Id.
    /// </summary>
    private async Task<int> SeedWalletAsync(int parentId = 1)
    {
        var now = DateTime.UtcNow.ToString("o");
        await _db.Database.ExecuteSqlRawAsync(
            $"""
            INSERT INTO "FamilyEnergyAccounts"
                ("ParentUserId","SubscriptionBalance","PurchasedBalance","xmin","CreatedAt","CreatedBy")
            VALUES
                ({parentId},0,0,1,'{now}',0)
            """);

        return await _db.FamilyEnergyAccounts
            .AsNoTracking()
            .Where(w => w.ParentUserId == parentId)
            .Select(w => w.Id)
            .FirstAsync();
    }

    /// <summary>
    /// Seeds a SeatReservation using standard EF (no xmin column).
    /// </summary>
    private async Task SeedActiveSeatAsync(int subscriptionId, int childId, int parentId = 1, SeatState seatState = SeatState.Active)
    {
        var reservation = new SeatReservation
        {
            SubscriptionId = subscriptionId,
            ChildId        = childId,
            ParentUserId   = parentId,
            Status         = SeatStatus.Active,
            SeatState      = seatState,
            ReservedAt     = DateTime.UtcNow,
            CreatedAt      = DateTime.UtcNow,
            CreatedBy      = 0,
        };
        _db.SeatReservations.Add(reservation);
        await _db.SaveChangesAsync();
    }

    /// <summary>
    /// Seeds a ChildEnergyAllocation via raw SQL because the entity has uint Version mapped
    /// to the Postgres xmin system column — SQLite won't auto-generate it.
    /// </summary>
    private async Task SeedAllocationAsync(int walletId, int childId, int allocated, int spent)
    {
        var now        = DateTime.UtcNow.ToString("o");
        var cycleStart = DateTime.UtcNow.AddDays(-15).ToString("o");
        var cycleEnd   = DateTime.UtcNow.AddDays(15).ToString("o");
        await _db.Database.ExecuteSqlRawAsync(
            $"""
            INSERT INTO "ChildEnergyAllocations"
                ("FamilyEnergyAccountId","ChildId","CycleStartUtc","CycleEndUtc",
                 "AllocatedAmount","SpentAmount","xmin","CreatedAt","CreatedBy")
            VALUES
                ({walletId},{childId},'{cycleStart}','{cycleEnd}',
                 {allocated},{spent},1,'{now}',0)
            """);
    }

    /// <summary>
    /// Resolves the ChildEnergyAllocation Id for a given child in a wallet (needed for ledger assertions).
    /// </summary>
    private async Task<int> GetAllocationIdAsync(int walletId, int childId)
        => await _db.ChildEnergyAllocations
            .AsNoTracking()
            .Where(a => a.FamilyEnergyAccountId == walletId && a.ChildId == childId)
            .Select(a => a.Id)
            .FirstAsync();

    // ── AT-01: fromChildId not in family ─────────────────────────────────────────────────────

    [Fact]
    public async Task AT01_FromChildId_NotInFamily_Returns_ChildNotInFamily()
    {
        var sub      = await SeedSubscriptionAsync(parentId: 1);
        var walletId = await SeedWalletAsync(parentId: 1);
        await SeedActiveSeatAsync(sub.Id, childId: 10);
        await SeedAllocationAsync(walletId, childId: 10, allocated: 200, spent: 0);

        // fromChildId=99 has NO active seat in this family.
        _seatStateQueryMock.Setup(x => x.IsChildSeatActiveAsync(It.IsAny<int>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(true);

        var svc    = BuildService();
        var result = await svc.TransferAllocationAsync(1, fromChildId: 99, toChildId: 10, 50, "key-001");

        result.Succeeded.Should().BeFalse();
        result.FailureReason.Should().Be(TransferAllocationFailureReason.ChildNotInFamily);
    }

    // ── AT-02: toChildId not in family ───────────────────────────────────────────────────────

    [Fact]
    public async Task AT02_ToChildId_NotInFamily_Returns_ChildNotInFamily()
    {
        var sub      = await SeedSubscriptionAsync(parentId: 1);
        var walletId = await SeedWalletAsync(parentId: 1);
        await SeedActiveSeatAsync(sub.Id, childId: 10);
        await SeedAllocationAsync(walletId, childId: 10, allocated: 200, spent: 0);

        // toChildId=99 has NO active seat in this family.
        _seatStateQueryMock.Setup(x => x.IsChildSeatActiveAsync(It.IsAny<int>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(true);

        var svc    = BuildService();
        var result = await svc.TransferAllocationAsync(1, fromChildId: 10, toChildId: 99, 50, "key-002");

        result.Succeeded.Should().BeFalse();
        result.FailureReason.Should().Be(TransferAllocationFailureReason.ChildNotInFamily);
    }

    // ── AT-03: amount > source.Remaining ─────────────────────────────────────────────────────

    [Fact]
    public async Task AT03_Amount_Exceeds_Remaining_Returns_AmountExceedsRemaining()
    {
        var sub      = await SeedSubscriptionAsync(parentId: 1);
        var walletId = await SeedWalletAsync(parentId: 1);
        await SeedActiveSeatAsync(sub.Id, childId: 10);
        await SeedActiveSeatAsync(sub.Id, childId: 20);
        await SeedAllocationAsync(walletId, childId: 10, allocated: 100, spent: 0);
        await SeedAllocationAsync(walletId, childId: 20, allocated: 50, spent: 0);

        _seatStateQueryMock.Setup(x => x.IsChildSeatActiveAsync(It.IsAny<int>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(true);

        var svc    = BuildService();
        // 101 > source.Remaining (100) → reject
        var result = await svc.TransferAllocationAsync(1, fromChildId: 10, toChildId: 20, 101, "key-003");

        result.Succeeded.Should().BeFalse();
        result.FailureReason.Should().Be(TransferAllocationFailureReason.AmountExceedsRemaining);
    }

    // ── AT-04: amount = 0 → AmountExceedsRemaining ───────────────────────────────────────────

    [Fact]
    public async Task AT04_Zero_Amount_Returns_AmountExceedsRemaining()
    {
        var sub      = await SeedSubscriptionAsync(parentId: 1);
        var walletId = await SeedWalletAsync(parentId: 1);
        await SeedActiveSeatAsync(sub.Id, childId: 10);
        await SeedActiveSeatAsync(sub.Id, childId: 20);
        await SeedAllocationAsync(walletId, childId: 10, allocated: 100, spent: 0);

        _seatStateQueryMock.Setup(x => x.IsChildSeatActiveAsync(It.IsAny<int>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(true);

        var svc    = BuildService();
        var result = await svc.TransferAllocationAsync(1, fromChildId: 10, toChildId: 20, 0, "key-004");

        result.Succeeded.Should().BeFalse();
        result.FailureReason.Should().Be(TransferAllocationFailureReason.AmountExceedsRemaining);
    }

    // ── AT-05: only UNSPENT is movable ────────────────────────────────────────────────────────

    [Fact]
    public async Task AT05_OnlyUnspentMovable_Transfer41_Fails_Transfer40_Succeeds()
    {
        var sub      = await SeedSubscriptionAsync(parentId: 1);
        var walletId = await SeedWalletAsync(parentId: 1);
        await SeedActiveSeatAsync(sub.Id, childId: 10);
        await SeedActiveSeatAsync(sub.Id, childId: 20);
        // Allocated=100, Spent=60 → Remaining=40
        await SeedAllocationAsync(walletId, childId: 10, allocated: 100, spent: 60);
        await SeedAllocationAsync(walletId, childId: 20, allocated: 50, spent: 0);

        _seatStateQueryMock.Setup(x => x.IsChildSeatActiveAsync(It.IsAny<int>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(true);

        var svc = BuildService();

        // Transfer 41 → fails (exceeds Remaining=40).
        var fail = await svc.TransferAllocationAsync(1, fromChildId: 10, toChildId: 20, 41, "key-005a");
        fail.Succeeded.Should().BeFalse();
        fail.FailureReason.Should().Be(TransferAllocationFailureReason.AmountExceedsRemaining);

        // Transfer 40 → succeeds.
        var ok = await svc.TransferAllocationAsync(1, fromChildId: 10, toChildId: 20, 40, "key-005b");
        ok.Succeeded.Should().BeTrue();
        ok.Data.Should().NotBeNull();

        // source: Allocated=100, Spent was 60, SendTransfer adds 40 → SpentAmount=100 → Remaining=0.
        ok.Data!.FromChild.Remaining.Should().Be(0);
        // dest: Allocated was 50, ReceiveTransfer adds 40 → AllocatedAmount=90 → Remaining=90.
        ok.Data.ToChild.Remaining.Should().Be(90);
    }

    // ── AT-06: mid-cycle child INSERT-then-transfer ───────────────────────────────────────────

    [Fact]
    public async Task AT06_MidCycle_DestHasNoAllocationRow_InsertsRow_AndTransferSucceeds()
    {
        var sub      = await SeedSubscriptionAsync(parentId: 1);
        var walletId = await SeedWalletAsync(parentId: 1);
        await SeedActiveSeatAsync(sub.Id, childId: 10);
        await SeedActiveSeatAsync(sub.Id, childId: 20); // mid-cycle child — no alloc row
        await SeedAllocationAsync(walletId, childId: 10, allocated: 200, spent: 0);
        // childId=20 has NO ChildEnergyAllocation row.

        _seatStateQueryMock.Setup(x => x.IsChildSeatActiveAsync(It.IsAny<int>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(true);

        var svc    = BuildService();
        var result = await svc.TransferAllocationAsync(1, fromChildId: 10, toChildId: 20, 50, "key-006");

        result.Succeeded.Should().BeTrue("mid-cycle child with active seat is a valid destination");
        result.Data.Should().NotBeNull();
        result.Data!.ToChild.ChildId.Should().Be(20);
        result.Data.ToChild.Remaining.Should().Be(50);

        // Verify the INSERT happened.
        var destRow = await _db.ChildEnergyAllocations
            .AsNoTracking()
            .Where(a => a.FamilyEnergyAccountId == walletId && a.ChildId == 20)
            .FirstOrDefaultAsync();
        destRow.Should().NotBeNull("a ChildEnergyAllocation row must be created for the mid-cycle destination child");
        // After ReceiveTransfer: AllocatedAmount = 0+50 = 50; SpentAmount = 0; Remaining = 50.
        destRow!.AllocatedAmount.Should().Be(50);
        destRow.SpentAmount.Should().Be(0);
    }

    // ── AT-07: paired ledger rows with shared CorrelationId ──────────────────────────────────

    [Fact]
    public async Task AT07_PairedLedgerRows_ShareCorrelationId()
    {
        var sub      = await SeedSubscriptionAsync(parentId: 1);
        var walletId = await SeedWalletAsync(parentId: 1);
        await SeedActiveSeatAsync(sub.Id, childId: 10);
        await SeedActiveSeatAsync(sub.Id, childId: 20);
        await SeedAllocationAsync(walletId, childId: 10, allocated: 200, spent: 0);
        await SeedAllocationAsync(walletId, childId: 20, allocated: 100, spent: 0);

        var srcAllocId  = await GetAllocationIdAsync(walletId, 10);
        var destAllocId = await GetAllocationIdAsync(walletId, 20);

        _seatStateQueryMock.Setup(x => x.IsChildSeatActiveAsync(It.IsAny<int>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(true);

        var svc    = BuildService();
        var result = await svc.TransferAllocationAsync(1, fromChildId: 10, toChildId: 20, 75, "key-007");

        result.Succeeded.Should().BeTrue();

        var txOut = await _db.CreditTransactions
            .AsNoTracking()
            .Where(t => t.ChildEnergyAllocationId == srcAllocId
                     && t.ReasonCode == CreditReasonCode.TransferOut)
            .FirstOrDefaultAsync();

        var txIn = await _db.CreditTransactions
            .AsNoTracking()
            .Where(t => t.ChildEnergyAllocationId == destAllocId
                     && t.ReasonCode == CreditReasonCode.TransferIn)
            .FirstOrDefaultAsync();

        txOut.Should().NotBeNull("TransferOut ledger row must be appended for source child");
        txIn.Should().NotBeNull("TransferIn ledger row must be appended for destination child");

        txOut!.Amount.Should().Be(75);
        txIn!.Amount.Should().Be(75);

        txOut.CorrelationId.Should().NotBeNull("TransferOut must carry a CorrelationId");
        txIn.CorrelationId.Should().NotBeNull("TransferIn must carry a CorrelationId");
        txOut.CorrelationId.Should().Be(txIn.CorrelationId,
            "the paired ledger rows must share the same CorrelationId");

        txOut.SourceBucket.Should().Be(EnergyBucket.Subscription,
            "transfers touch bucket A (Subscription) only — never bucket B (Purchased)");
        txIn.SourceBucket.Should().Be(EnergyBucket.Subscription);
    }

    // ── AT-08: idempotency — same key does NOT double-move ───────────────────────────────────

    [Fact]
    public async Task AT08_Idempotency_SameKey_DoesNotDoubleMove()
    {
        var sub      = await SeedSubscriptionAsync(parentId: 1);
        var walletId = await SeedWalletAsync(parentId: 1);
        await SeedActiveSeatAsync(sub.Id, childId: 10);
        await SeedActiveSeatAsync(sub.Id, childId: 20);
        await SeedAllocationAsync(walletId, childId: 10, allocated: 200, spent: 0);
        await SeedAllocationAsync(walletId, childId: 20, allocated: 0, spent: 0);

        _seatStateQueryMock.Setup(x => x.IsChildSeatActiveAsync(It.IsAny<int>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(true);

        var svc = BuildService();

        // First call.
        var first = await svc.TransferAllocationAsync(1, 10, 20, 50, "key-008-idempotent");
        first.Succeeded.Should().BeTrue();

        // Second call with the same key.
        var second = await svc.TransferAllocationAsync(1, 10, 20, 50, "key-008-idempotent");
        second.Succeeded.Should().BeTrue("re-submit must return prior result without double-move");

        // Only ONE TransferOut row must exist (idempotency enforced on IdempotencyKey unique index).
        var outCount = await _db.CreditTransactions
            .AsNoTracking()
            .CountAsync(t => t.ReasonCode == CreditReasonCode.TransferOut
                          && t.IdempotencyKey == "transfer-out:key-008-idempotent");
        outCount.Should().Be(1, "idempotent replay must NOT append a second TransferOut row");

        // Source remaining must reflect exactly ONE transfer of 50, not two.
        var srcAlloc = await _db.ChildEnergyAllocations
            .AsNoTracking()
            .Where(a => a.FamilyEnergyAccountId == walletId && a.ChildId == 10)
            .FirstOrDefaultAsync();
        srcAlloc!.Remaining.Should().Be(150, "only 50 should have been moved, not 100");
    }

    // ── AT-09: GetFamilyAllocationAsync — IsMidCycleNoGrant=true for child with no alloc row ─

    [Fact]
    public async Task AT09_GetAllocation_MidCycleChild_HasIsMidCycleNoGrant_True()
    {
        var sub      = await SeedSubscriptionAsync(parentId: 1);
        var walletId = await SeedWalletAsync(parentId: 1);
        await SeedActiveSeatAsync(sub.Id, childId: 10);
        await SeedActiveSeatAsync(sub.Id, childId: 20); // mid-cycle child — no alloc row
        await SeedAllocationAsync(walletId, childId: 10, allocated: 300, spent: 50);
        // childId=20 has NO allocation row.

        _seatStateQueryMock.Setup(x => x.IsChildSeatActiveAsync(It.IsAny<int>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(true);

        var svc = BuildService();
        var dto = await svc.GetFamilyAllocationAsync(1);

        dto.Should().NotBeNull();
        dto!.Children.Should().HaveCount(2, "both active-seat children must appear");

        var child10 = dto.Children.Single(c => c.ChildId == 10);
        child10.IsMidCycleNoGrant.Should().BeFalse();
        child10.Remaining.Should().Be(250);

        var child20 = dto.Children.Single(c => c.ChildId == 20);
        child20.IsMidCycleNoGrant.Should().BeTrue("mid-cycle child with no allocation row must be flagged");
        child20.Allocated.Should().Be(0);
        child20.Spent.Should().Be(0);
        child20.Remaining.Should().Be(0);
    }

    // ── AT-10: GetFamilyAllocationAsync returns ALL active-seat children ──────────────────────

    [Fact]
    public async Task AT10_GetAllocation_ReturnsAll_ActiveSeatChildren_Including_ZeroAllocation()
    {
        var sub      = await SeedSubscriptionAsync(parentId: 1);
        var walletId = await SeedWalletAsync(parentId: 1);
        await SeedActiveSeatAsync(sub.Id, childId: 10);
        await SeedActiveSeatAsync(sub.Id, childId: 20);
        await SeedActiveSeatAsync(sub.Id, childId: 30);
        // Only childId=10 has an allocation row.
        await SeedAllocationAsync(walletId, childId: 10, allocated: 500, spent: 100);

        _seatStateQueryMock.Setup(x => x.IsChildSeatActiveAsync(It.IsAny<int>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(true);

        var svc = BuildService();
        var dto = await svc.GetFamilyAllocationAsync(1);

        dto.Should().NotBeNull();
        dto!.Children.Should().HaveCount(3, "all three active-seat children must appear");

        dto.Children.Where(c => !c.IsMidCycleNoGrant).Should().HaveCount(1,
            "only child 10 has a grant row");
        dto.Children.Where(c => c.IsMidCycleNoGrant).Should().HaveCount(2,
            "children 20 and 30 have no allocation row → IsMidCycleNoGrant=true");
    }
}
