<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Modules\Billing\Learnexia.Modules.Billing.Application\Learnexia.Modules.Billing.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Billing\Learnexia.Modules.Billing.Infrastructure\Learnexia.Modules.Billing.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Billing\Learnexia.Modules.Billing.Domain\Learnexia.Modules.Billing.Domain.csproj" />
    <ProjectReference Include="..\..\src\Shared\Learnexia.Shared.Contracts\Learnexia.Shared.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Shared\Learnexia.Shared.Resources\Learnexia.Shared.Resources.csproj" />
  </ItemGroup>
</Project>
