using Learnexia.Shared.Kernel.Entities;

namespace Learnexia.Modules.Learning.Domain.Entities;

/// <summary>
/// Persisted daily recommendation set for a student — the output of the
/// <c>RecommendationEngine</c> (P5-09).
///
/// One row per <c>(StudentId, RecommendationDate)</c>, enforced by a unique index.
/// The set is computed <b>deterministically</b> (rule-based, no LLM call) from
/// P5-02 weak areas + P3-08 target difficulty + P3-13 behavioral profile + grade.
///
/// <b>Module isolation:</b> <c>StudentId</c> is a loose <c>int</c> reference to the
/// Identity student user. There is NO cross-module foreign key.
///
/// <b>Grade-transition preservation:</b> this entity is per-student/per-day and
/// grade-agnostic. A grade change MUST NOT wipe historical rows; stale rows for a
/// prior grade roll off naturally the next day when the recompute job runs.
///
/// <b>ItemsJson:</b> holds a serialised <c>RecommendationItem[]</c> as <c>jsonb</c>.
/// The exact record type is defined in <c>Shared.Contracts/Learning</c> (P5-09-BE-5)
/// and serialised/deserialised by the application layer, not the DB — same pattern as
/// <c>StudentLearningProfile.QuestionTypeAffinity</c> and <c>ContentBlock.Payload</c>.
/// Column default is <c>'[]'</c> (valid empty JSON array).
/// </summary>
public class StudentRecommendation : FullAuditedEntity
{
    /// <summary>
    /// Loose reference to the Identity student user (plain int — NO cross-module FK).
    /// Composite unique index with <see cref="RecommendationDate"/> enforces one row
    /// per student per day (defined in <see cref="StudentRecommendationConfig"/>).
    /// </summary>
    public int StudentId { get; set; }

    /// <summary>
    /// The local calendar day this recommendation set was computed for.
    /// Combined with <see cref="StudentId"/> as the idempotency key for the daily
    /// upsert — the job writes exactly one row per <c>(student, date)</c>.
    /// Stored as <c>date</c> (no time component) in PostgreSQL.
    /// </summary>
    public DateOnly RecommendationDate { get; set; }

    /// <summary>
    /// Serialised <c>RecommendationItem[]</c> stored as <c>jsonb</c> in PostgreSQL.
    /// Default value is <c>'[]'</c> (empty JSON array) so cold-start / not-yet-computed
    /// rows are always valid JSON and never null.
    ///
    /// The <c>RecommendationItem</c> record is defined in
    /// <c>Shared.Contracts/Learning/IStudentRecommendationsQuery.cs</c> (P5-09-BE-5).
    /// Serialisation/deserialisation is owned by the application layer
    /// (<c>RecommendationService</c>).
    /// </summary>
    public string ItemsJson { get; set; } = "[]";

    /// <summary>
    /// UTC timestamp of when this recommendation set was generated by the
    /// <c>RecommendationRecomputeJob</c>. Stored as <c>timestamptz</c>.
    /// </summary>
    public DateTime GeneratedAtUtc { get; set; }
}
