// <auto-generated />
using System;
using Learnexia.Modules.Analytics.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Learnexia.Modules.Analytics.Infrastructure.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20260620224546_P9_11_AddNotificationFacetsToActivityEvent")]
    partial class P9_11_AddNotificationFacetsToActivityEvent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("analytics")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Learnexia.Modules.Analytics.Domain.Entities.ActivityEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("NotificationCategory")
                        .HasColumnType("integer");

                    b.Property<int?>("NotificationChannels")
                        .HasColumnType("integer");

                    b.Property<string>("NotificationCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("SourceEventId")
                        .HasColumnType("uuid");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int?>("SubjectCode")
                        .HasColumnType("integer");

                    b.Property<string>("SuppressionReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("EventType")
                        .HasDatabaseName("IX_ActivityEvents_EventType");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("IX_ActivityEvents_OccurredAtUtc");

                    b.HasIndex("SourceEventId")
                        .IsUnique()
                        .HasDatabaseName("IX_ActivityEvents_SourceEventId_Unique");

                    b.HasIndex("EventType", "OccurredAtUtc")
                        .HasDatabaseName("IX_ActivityEvents_EventType_OccurredAtUtc");

                    b.HasIndex("StudentId", "OccurredAtUtc")
                        .HasDatabaseName("IX_ActivityEvents_StudentId_OccurredAtUtc");

                    b.ToTable("ActivityEvents", "analytics");
                });
#pragma warning restore 612, 618
        }
    }
}
