using Learnexia.Modules.Gamification.Domain.Enums;
using Learnexia.Shared.Kernel.Entities;

namespace Learnexia.Modules.Gamification.Domain.Entities;

/// <summary>
/// League cohort row. One row per (Tier, PeriodKey, GroupIndex) combination.
/// Keyed by the unique index <c>UX_Leagues_Tier_PeriodKey_GroupIndex</c>.
///
/// Append-only after creation — a cohort never changes after it is instantiated.
/// Derives from <see cref="CreationAuditedEntity"/> (no admin edits planned).
///
/// <see cref="PeriodKey"/> format mirrors <c>StudentMission.PeriodKey</c> — e.g. "W:2026-23".
/// Generated by <c>MissionPeriodCalculator.GetCurrentPeriod(MissionType.Weekly, ...)</c>.
/// </summary>
public sealed class League : CreationAuditedEntity
{
    /// <summary>The tier this cohort competes in. Stored as int.</summary>
    public LeagueTier Tier { get; private set; }

    /// <summary>ISO-8601 week key — e.g. "W:2026-23". Mirrors StudentMission.PeriodKey format.</summary>
    public string PeriodKey { get; private set; } = null!;

    /// <summary>Monday 00:00 UTC — start of the competition period.</summary>
    public DateTime PeriodStartUtc { get; private set; }

    /// <summary>Next Monday 00:00 UTC — exclusive end of the competition period.</summary>
    public DateTime PeriodEndUtc { get; private set; }

    /// <summary>
    /// 1-based cohort ordinal within (Tier, PeriodKey). First cohort at a given tier+week = 1.
    /// Increments when an existing cohort is full (capacity reached).
    /// Used for display ("Student #N") and cohort overflow grouping.
    /// </summary>
    public int GroupIndex { get; private set; }

    /// <summary>
    /// Snapshot of <c>LeagueOptions.CohortSize</c> at cohort creation time.
    /// Defaults 30. Stored so that rollover logic uses the cap that was in effect when the
    /// cohort was created, not the current config value.
    /// </summary>
    public int Capacity { get; private set; }

    /// <summary>Navigation: all memberships in this cohort.</summary>
    public ICollection<LeagueMembership> Memberships { get; private set; } = new List<LeagueMembership>();

    // ---------------------------------------------------------------------------
    // EF constructor
    // ---------------------------------------------------------------------------

    private League() { }

    // ---------------------------------------------------------------------------
    // Factory
    // ---------------------------------------------------------------------------

    /// <summary>
    /// Creates a new league cohort. All properties are set; no mutation is expected after creation.
    /// </summary>
    public static League Create(
        LeagueTier tier,
        string periodKey,
        DateTime periodStartUtc,
        DateTime periodEndUtc,
        int groupIndex,
        int capacity)
        => new()
        {
            Tier = tier,
            PeriodKey = periodKey,
            PeriodStartUtc = periodStartUtc,
            PeriodEndUtc = periodEndUtc,
            GroupIndex = groupIndex,
            Capacity = capacity,
        };
}
