<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Learnexia.Modules.Analytics.Api</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MediatR" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Learnexia.Modules.Analytics.Application\Learnexia.Modules.Analytics.Application.csproj" />
    <ProjectReference Include="..\Learnexia.Modules.Analytics.Infrastructure\Learnexia.Modules.Analytics.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\Shared\Learnexia.Shared.Kernel\Learnexia.Shared.Kernel.csproj" />
  </ItemGroup>
</Project>
