// <auto-generated />
using System;
using Learnexia.Modules.Curriculum.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Learnexia.Modules.Curriculum.Infrastructure.Migrations
{
    [DbContext(typeof(CurriculumDbContext))]
    partial class CurriculumDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("curriculum")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Learnexia.Modules.Curriculum.Domain.Entities.ChunkEmbeddingBgeM3", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChunkId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("Dimension")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Vector>("Vector")
                        .IsRequired()
                        .HasColumnType("vector(1024)");

                    b.HasKey("Id");

                    b.HasIndex("ChunkId")
                        .HasDatabaseName("ix_chunk_embeddings_bge_m3_chunk_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_chunk_embeddings_bge_m3_is_active");

                    b.HasIndex("Vector")
                        .HasDatabaseName("ix_chunk_embeddings_bge_m3_vector_hnsw_cosine");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Vector"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Vector"), new[] { "vector_cosine_ops" });

                    b.ToTable("chunk_embeddings_bge_m3", "curriculum");
                });

            modelBuilder.Entity("Learnexia.Modules.Curriculum.Domain.Entities.CurriculumChunk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConceptId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("CurriculumVersionId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<int>("GradeId")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Language")
                        .HasColumnType("integer");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}");

                    b.Property<string>("ProvenanceRef")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int?>("SkillId")
                        .HasColumnType("integer");

                    b.Property<string>("SkillKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumVersionId")
                        .HasDatabaseName("ix_curriculum_chunks_version_id");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("ix_curriculum_chunks_skill_id");

                    b.HasIndex("SkillKey")
                        .HasDatabaseName("ix_curriculum_chunks_skill_key");

                    b.HasIndex("GradeId", "SubjectId")
                        .HasDatabaseName("ix_curriculum_chunks_grade_subject");

                    b.ToTable("CurriculumChunks", "curriculum");
                });

            modelBuilder.Entity("Learnexia.Modules.Curriculum.Domain.Entities.CurriculumVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Language")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId", "Language")
                        .IsUnique()
                        .HasDatabaseName("ix_curriculum_versions_active_subject_language")
                        .HasFilter("\"Status\" = 1");

                    b.ToTable("CurriculumVersions", "curriculum");
                });

            modelBuilder.Entity("Learnexia.Modules.Curriculum.Domain.Entities.ChunkEmbeddingBgeM3", b =>
                {
                    b.HasOne("Learnexia.Modules.Curriculum.Domain.Entities.CurriculumChunk", "Chunk")
                        .WithMany("Embeddings")
                        .HasForeignKey("ChunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chunk");
                });

            modelBuilder.Entity("Learnexia.Modules.Curriculum.Domain.Entities.CurriculumChunk", b =>
                {
                    b.HasOne("Learnexia.Modules.Curriculum.Domain.Entities.CurriculumVersion", "CurriculumVersion")
                        .WithMany("Chunks")
                        .HasForeignKey("CurriculumVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurriculumVersion");
                });

            modelBuilder.Entity("Learnexia.Modules.Curriculum.Domain.Entities.CurriculumChunk", b =>
                {
                    b.Navigation("Embeddings");
                });

            modelBuilder.Entity("Learnexia.Modules.Curriculum.Domain.Entities.CurriculumVersion", b =>
                {
                    b.Navigation("Chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
