using Learnexia.Shared.Kernel.Entities;

namespace Learnexia.Modules.Parent.Domain.Entities;

/// <summary>
/// Persisted weekly report for a single child, generated by the Hangfire scheduled job
/// (P5-01-BE-3) for the prior calendar week.
///
/// <para>Design decisions:</para>
/// <list type="bullet">
///   <item><see cref="ChildId"/> — plain <c>int</c>, NO cross-module FK (module isolation rule 1).
///   Child accounts live in Identity and are reached via the IChildAccountService seam.</item>
///   <item><see cref="WeekStartUtc"/> — Monday 00:00 UTC of the report week; combined with
///   <see cref="ChildId"/> this is the logical unique key (idempotent per-week upsert).</item>
///   <item><see cref="WeakAreasJson"/> and <see cref="RecommendationsJson"/> — serialized
///   JSON snapshots stored as <c>jsonb</c> for queryability. Application layer owns the shape.</item>
///   <item>Derives from <see cref="FullAuditedEntity"/> — picks up <c>Id</c>, <c>CreatedAt</c>,
///   <c>CreatedBy</c>, <c>UpdatedAt</c>, <c>UpdatedBy</c>, <c>DeletedAt</c>, <c>DeletedBy</c>,
///   <c>IsDeleted</c>. <c>ParentDbContext.SaveChangesAsync(int userId)</c> stamps the audit
///   fields automatically.</item>
/// </list>
///
/// <para>References: P5-01-BE-1 (migration), P5-01-BE-2 (generator service), P5-01-BE-4 (E9 read).</para>
/// </summary>
public class WeeklyReport : FullAuditedEntity
{
    /// <summary>
    /// The child (student) this report belongs to. Plain int — no cross-module FK.
    /// </summary>
    public int ChildId { get; set; }

    /// <summary>
    /// Monday 00:00 UTC of the report week. Combined with <see cref="ChildId"/> this is
    /// the unique business key; a UNIQUE index enforces idempotent per-week upsert.
    /// Stored as <c>timestamp with time zone</c> (UTC).
    /// </summary>
    public DateTime WeekStartUtc { get; set; }

    /// <summary>
    /// XP the child earned during the report week (aggregate from Gamification seam).
    /// </summary>
    public int XpEarned { get; set; }

    /// <summary>
    /// Number of distinct skills whose mastery improved during the report week
    /// (aggregate from Learning seam).
    /// </summary>
    public int SkillsImproved { get; set; }

    /// <summary>
    /// JSON snapshot of the child's weak areas as of the end of the report week.
    /// Serialized from the P5-02 weak-area detector output; stored as <c>jsonb</c>.
    /// Application layer owns the JSON shape. Default is an empty array string.
    /// </summary>
    public string WeakAreasJson { get; set; } = "[]";

    /// <summary>
    /// JSON array of recommendations generated for the child based on the week's weak areas.
    /// Stored as <c>jsonb</c>. Application layer owns the JSON shape. Default is an empty array string.
    /// </summary>
    public string RecommendationsJson { get; set; } = "[]";

    /// <summary>
    /// UTC timestamp when this report row was generated (or last regenerated on idempotent upsert).
    /// Stored as <c>timestamp with time zone</c> (UTC).
    /// </summary>
    public DateTime GeneratedAtUtc { get; set; }
}
