/**
 * FE-local DTO interfaces for the P7-01..P7-05 admin curriculum hooks.
 *
 * These are hand-written mirrors of the backend Learning module DTOs — they are
 * NOT generated by NSwag (admin curriculum DTOs are not in the NSwag client).
 * Update these when the backend contract changes.
 *
 * Enum fields (`subjectCode`, `language`) arrive on the wire as ints. Import
 * `SUBJECT_CODE` + `CONTENT_LANGUAGE` from `@learnexia/shared/constants` for
 * comparisons — never use raw int literals.
 */

import type { SubjectCodeValue, ContentLanguageValue } from '@learnexia/shared/constants';

// ── P7-01 Subject DTOs ────────────────────────────────────────────────────────

/**
 * Single subject as returned by `GET /api/learning/Subjects/List` (paginated)
 * and `GET /api/learning/Subjects?id=` (single).
 */
export interface SubjectDto {
  id: number;
  name: string;
  country?: string | null;
  gradeId: number;
  /** SubjectCode enum as int: MATH=0, SCIENCE=1, ARABIC=2, ENGLISH=3 */
  subjectCode: SubjectCodeValue;
  /** ContentLanguage enum as int: Ar=0, En=1 */
  language: ContentLanguageValue;
  sequenceOrder: number;
  isActive: boolean;
}

/** Body for `POST /api/learning/Subjects/Create`. */
export interface AddSubjectDto {
  name: string;
  gradeId: number;
  subjectCode: SubjectCodeValue;
  language: ContentLanguageValue;
  sequenceOrder: number;
  isActive: boolean;
}

/** Body for `PUT /api/learning/Subjects/Update`. */
export interface EditSubjectDto {
  id: number;
  name: string;
  gradeId: number;
  subjectCode: SubjectCodeValue;
  language: ContentLanguageValue;
  sequenceOrder: number;
  isActive: boolean;
}

// ── P7-01 Unit DTOs ───────────────────────────────────────────────────────────

/**
 * Single unit as returned by `GET /api/learning/Units/List?SubjectId=` (paginated)
 * and `GET /api/learning/Units?id=` (single).
 *
 * Units do NOT carry a `language` field — they inherit it from the owning Subject.
 * Always carry the parent subject's `language` down the tree via navigation state.
 */
export interface UnitDto {
  id: number;
  name: string;
  sequenceOrder: number;
  subjectId: number;
  isActive: boolean;
}

/** Body for `POST /api/learning/Units/Create`. */
export interface AddUnitDto {
  name: string;
  subjectId: number;
  sequenceOrder: number;
  isActive: boolean;
}

/** Body for `PUT /api/learning/Units/Update`. */
export interface EditUnitDto {
  id: number;
  name: string;
  subjectId: number;
  sequenceOrder: number;
  isActive: boolean;
}

// ── P7-01 Coverage DTOs ───────────────────────────────────────────────────────

/**
 * One slot in the 6-slot coverage grid for a grade.
 * Fixed order: MATH/Ar, MATH/En, SCIENCE/Ar, SCIENCE/En, ARABIC/Ar, ENGLISH/En.
 */
export interface SubjectLanguageCoverageDto {
  subjectCode: SubjectCodeValue;
  language: ContentLanguageValue;
  exists: boolean;
  subjectId: number | null;
  name: string | null;
  isActive: boolean | null;
}

/** Full coverage report for a grade (`GET /api/learning/Subjects/Coverage?gradeId=`). */
export interface SubjectLanguageCoverageReportDto {
  gradeId: number;
  gradeNumber: number;
  coverage: SubjectLanguageCoverageDto[];
  gapCount: number;
}

// ── P7-01 Grade DTO ───────────────────────────────────────────────────────────

/** Grade entry from `GET /api/learning/Grades/List`. */
export interface GradeDto {
  id: number;
  gradeNumber: number;
  name?: string | null;
}

// ── P7-02 Lesson / ContentBlock DTOs (stubs — P7-02 batch fills these) ───────

/** Lesson list item — stub for P7-02. */
export interface LessonDto {
  id: number;
  name: string;
  unitId: number;
  sequenceOrder: number;
  isActive: boolean;
}

/** Content block — stub for P7-02. */
export interface AdminContentBlockDto {
  id: number;
  lessonId: number;
  blockType: number;
  content: string;
  sequenceOrder: number;
}

// ── P7-04 Question DTO (stub — P7-04 batch fills this) ───────────────────────

/** Question list item — stub for P7-04. */
export interface AdminQuestionDto {
  id: number;
  lessonId: number;
  questionType: number;
  questionText: string;
  sequenceOrder: number;
  isActive: boolean;
  correctAnswer: string;
  options?: string | null;
}

// ── P7-03 Skill / Graph DTOs (stubs — P7-03 batch fills these) ───────────────

/** Skill node — stub for P7-03. */
export interface SkillDto {
  id: number;
  name: string;
  subjectId: number;
  masteryThreshold: number;
  timeToMasterMinutes?: number | null;
  conceptId?: number | null;
  isActive: boolean;
}

/** Skill graph — stub for P7-03. */
export interface SkillGraphDto {
  nodes: SkillDto[];
  edges: Array<{ fromNodeId: number; toNodeId: number; relationshipType: number; strength: number }>;
}
