/**
 * FE-local DTO interfaces for the P7-01..P7-05 admin curriculum hooks.
 *
 * These are hand-written mirrors of the backend Learning module DTOs — they are
 * NOT generated by NSwag (admin curriculum DTOs are not in the NSwag client).
 * Update these when the backend contract changes.
 *
 * Enum fields (`subjectCode`, `language`) arrive on the wire as ints. Import
 * `SUBJECT_CODE` + `CONTENT_LANGUAGE` from `@learnexia/shared/constants` for
 * comparisons — never use raw int literals.
 */

import type { SubjectCodeValue, ContentLanguageValue, DifficultyLevelValue, ContentBlockTypeValue, QuestionTypeValue, GeneratedByValue, NodeTypeValue, RelationshipTypeValue } from '@learnexia/shared/constants';

// ── P7-01 Subject DTOs ────────────────────────────────────────────────────────

/**
 * Single subject as returned by `GET /api/learning/Subjects/List` (paginated)
 * and `GET /api/learning/Subjects?id=` (single).
 */
export interface SubjectDto {
  id: number;
  name: string;
  country?: string | null;
  gradeId: number;
  /** SubjectCode enum as int: MATH=0, SCIENCE=1, ARABIC=2, ENGLISH=3 */
  subjectCode: SubjectCodeValue;
  /** ContentLanguage enum as int: Ar=0, En=1 */
  language: ContentLanguageValue;
  sequenceOrder: number;
  isActive: boolean;
}

/** Body for `POST /api/learning/Subjects/Create`. */
export interface AddSubjectDto {
  name: string;
  gradeId: number;
  subjectCode: SubjectCodeValue;
  language: ContentLanguageValue;
  sequenceOrder: number;
  isActive: boolean;
}

/** Body for `PUT /api/learning/Subjects/Update`. */
export interface EditSubjectDto {
  id: number;
  name: string;
  gradeId: number;
  subjectCode: SubjectCodeValue;
  language: ContentLanguageValue;
  sequenceOrder: number;
  isActive: boolean;
}

// ── P7-01 Unit DTOs ───────────────────────────────────────────────────────────

/**
 * Single unit as returned by `GET /api/learning/Units/List?SubjectId=` (paginated)
 * and `GET /api/learning/Units?id=` (single).
 *
 * Units do NOT carry a `language` field — they inherit it from the owning Subject.
 * Always carry the parent subject's `language` down the tree via navigation state.
 */
export interface UnitDto {
  id: number;
  name: string;
  sequenceOrder: number;
  subjectId: number;
  isActive: boolean;
}

/** Body for `POST /api/learning/Units/Create`. */
export interface AddUnitDto {
  name: string;
  subjectId: number;
  sequenceOrder: number;
  isActive: boolean;
}

/** Body for `PUT /api/learning/Units/Update`. */
export interface EditUnitDto {
  id: number;
  name: string;
  subjectId: number;
  sequenceOrder: number;
  isActive: boolean;
}

// ── P7-01 Coverage DTOs ───────────────────────────────────────────────────────

/**
 * One slot in the 6-slot coverage grid for a grade.
 * Fixed order: MATH/Ar, MATH/En, SCIENCE/Ar, SCIENCE/En, ARABIC/Ar, ENGLISH/En.
 */
export interface SubjectLanguageCoverageDto {
  subjectCode: SubjectCodeValue;
  language: ContentLanguageValue;
  exists: boolean;
  subjectId: number | null;
  name: string | null;
  isActive: boolean | null;
}

/** Full coverage report for a grade (`GET /api/learning/Subjects/Coverage?gradeId=`). */
export interface SubjectLanguageCoverageReportDto {
  gradeId: number;
  gradeNumber: number;
  coverage: SubjectLanguageCoverageDto[];
  gapCount: number;
}

// ── P7-01 Grade DTO ───────────────────────────────────────────────────────────

/** Grade entry from `GET /api/learning/Grades/List`. */
export interface GradeDto {
  id: number;
  gradeNumber: number;
  name?: string | null;
}

// ── P7-02 Lesson / ContentBlock DTOs ─────────────────────────────────────────

/**
 * Wire shape from GET /api/learning/Lessons/List?UnitId={id} (paginated, AdminOnly).
 * Admin list includes inactive lessons.
 *
 * Named AdminSingleLessonResponse to avoid collision with the NSwag-generated
 * student-facing SingleLessonResponse in schemas.ts.
 */
export interface AdminSingleLessonResponse {
  id: number;
  name: string;
  /** DifficultyLevel enum as int: Easy=1, Medium=2, Hard=3 */
  difficulty: DifficultyLevelValue;
  sequenceOrder: number;
  isLocked: boolean;
  unitId: number;
  skillId: number | null;
  estimatedMinutes: number;
  isActive: boolean;
}

/**
 * Wire shape from GET /api/learning/Lessons/{id}/Admin.
 * Returns lesson metadata + all non-deleted blocks ordered by sequenceOrder.
 */
export interface AdminLessonDetailDto {
  id: number;
  name: string;
  difficulty: DifficultyLevelValue;
  sequenceOrder: number;
  isLocked: boolean;
  unitId: number;
  skillId: number | null;
  estimatedMinutes: number;
  isActive: boolean;
  contentBlocks: AdminContentBlockDto[];
}

/**
 * Wire shape for a single content block (from AdminLessonDetailDto or ByLesson).
 * isActive is display-only — no toggle endpoint (brief Q4).
 */
export interface AdminContentBlockDto {
  id: number;
  /** ContentBlockType enum as int: Text=1, Image=2, Video=3, Callout=4 */
  blockType: ContentBlockTypeValue;
  /** JSON string — parse per type using ParsedPayload union */
  payload: string;
  sequenceOrder: number;
  isActive: boolean;
}

/** Body for POST /api/learning/Lessons/Create (AddLessonCommand). */
export interface AddLessonDto {
  name: string;
  difficulty: DifficultyLevelValue;
  sequenceOrder: number;
  isLocked: boolean;
  unitId: number;
  skillId?: number | null;
  estimatedMinutes: number;
}

/** Body for PUT /api/learning/Lessons/Update (EditLessonCommand). */
export interface EditLessonDto {
  id: number;
  name: string;
  difficulty: DifficultyLevelValue;
  sequenceOrder: number;
  isLocked: boolean;
  unitId: number;
  skillId?: number | null;
  estimatedMinutes: number;
}

// ── Parsed payload shapes (FE-only; never sent raw — always re-serialize to JSON) ──

export interface TextPayload    { markdown: string; }
export interface ImagePayload   { url: string; altText?: string; }
export interface VideoPayload   { url: string; caption?: string; }
export interface CalloutPayload { variant: 'info' | 'warning' | 'tip'; markdown: string; }

export type ParsedPayload = TextPayload | ImagePayload | VideoPayload | CalloutPayload;

/** Body for POST /api/learning/ContentBlocks (add block). */
export interface AddContentBlockDto {
  lessonId: number;
  blockType: ContentBlockTypeValue;
  /** JSON-serialized payload string (exact per-type shape) */
  payload: string;
}

/** Body for PUT /api/learning/ContentBlocks (edit block). */
export interface EditContentBlockDto {
  id: number;
  blockType: ContentBlockTypeValue;
  payload: string;
}

/** Alias retained for compatibility */
export interface LessonDto {
  id: number;
  name: string;
  unitId: number;
  sequenceOrder: number;
  isActive: boolean;
}

// ── P7-04 Question DTOs ────────────────────────────────────────────────────────

/**
 * Wire shape returned from:
 *   GET /api/Learning/Questions/ByLesson/{lessonId}  (list, AdminOnly)
 *   GET /api/Learning/Questions/{id}                  (single, AdminOnly)
 *
 * LOAD-BEARING contract for options/correctAnswer:
 *  - Non-Matching: correctAnswer is a RAW SCALAR (e.g. "Paris", "true").
 *    DO NOT JSON.parse it on read; DO NOT JSON.stringify it on write.
 *  - Matching: options and correctAnswer are both JSON object strings.
 *    Parse with try/catch on read; JSON.stringify on write.
 */
export interface AdminQuestionDto {
  id: number;
  lessonId: number;
  skillId: number | null;
  /** QuestionType enum as int: MCQ=1, TrueFalse=2, Matching=3, FillInBlank=4 */
  questionType: QuestionTypeValue;
  questionText: string;
  /** JSON string — parse per type (see LOAD-BEARING section in P7-04 brief/spec) */
  options: string;
  /** Raw scalar or JSON object string — see per-type rules in P7-04 brief/spec */
  correctAnswer: string;
  /** DifficultyLevel enum as int: Easy=1, Medium=2, Hard=3 */
  difficulty: DifficultyLevelValue;
  /** GeneratedBy enum as int: Curated=1, AI=2 */
  generatedBy: GeneratedByValue;
  sequenceOrder: number;
  isActive: boolean;
}

/** POST body for AddQuestionCommand. */
export interface AddQuestionPayload {
  lessonId: number;
  skillId?: number | null;
  questionType: QuestionTypeValue;
  questionText: string;
  /** JSON-serialized options string — per-type rules in P7-04 spec */
  options: string;
  /** Per-type correctAnswer — raw scalar for non-Matching; JSON string for Matching */
  correctAnswer: string;
  difficulty: DifficultyLevelValue;
  /** Always GENERATED_BY.Curated (=1) for admin-authored questions */
  generatedBy: GeneratedByValue;
}

/** PUT body for EditQuestionCommand. */
export interface EditQuestionPayload {
  id: number;
  questionType: QuestionTypeValue;
  questionText: string;
  options: string;
  correctAnswer: string;
  difficulty: DifficultyLevelValue;
  // NOTE: lessonId/skillId/sequenceOrder/isActive intentionally absent
}

// ── P7-03 Skill / Graph DTOs ─────────────────────────────────────────────────
//
// Replaces the stubs from the 2a-A batch with the real DTOs derived from
// the merged backend Learning module contracts (verified against the controllers
// in docs/briefs/P7-03-FE.md §Exact endpoints).

/**
 * Wire shape from GET /api/learning/Skills/List (PaginatedResult<SingleSkillResponse>)
 * and GET /api/learning/Skills?id={id}.
 *
 * Backend: SingleSkillResponse extends SkillDto, adds IsActive.
 * All fields are from the admin-only endpoints — IsActive is ALWAYS present
 * (verified: SingleSkillResponse.cs explicitly sets it).
 *
 * Gap 2 RESOLVED: isActive IS present on the wire (admin-only endpoint).
 * The Active column and toggle are therefore always rendered.
 */
export interface SingleSkillResponse {
  id: number;
  name: string;
  masteryThreshold: number;       // int 0–100
  estimatedTimeMinutes: number;   // int ≥ 0
  conceptId: number;              // owning concept node id
  isActive: boolean;              // always present (AdminOnly endpoint)
}

/** POST body for POST /api/learning/Skills/Create (AddSkillCommand). */
export interface AddSkillDto {
  name: string;
  masteryThreshold: number;   // 0–100
  estimatedTimeMinutes: number;
  conceptId: number;          // must be > 0
}

/** PUT body for PUT /api/learning/Skills/Update (EditSkillCommand). */
export interface EditSkillDto {
  id: number;
  name: string;
  masteryThreshold: number;
  estimatedTimeMinutes: number;
  conceptId: number;
}

/**
 * Node in the full graph (from SkillGraphDto).
 * Returned by GET /api/Learning/KnowledgeGraph/Graph?subjectId=.
 * The `id` field is the KnowledgeNode.Id — use for all edge endpoints.
 */
export interface KnowledgeNodeDto {
  id: number;                           // KnowledgeNode.Id — use for edges
  name: string;
  nodeType: NodeTypeValue;              // 0 Skill | 1 Concept | 2 Review
  subjectId: number;
  gradeId: number;
  difficulty: number;
  skillId?: number | null;              // non-null only when nodeType===Skill
  isSkillActive?: boolean | null;       // admin-only field; null for non-skill nodes
}

/**
 * Edge in the full graph.
 * Returned by GET /api/Learning/KnowledgeGraph/Graph?subjectId=.
 * `id` is the KnowledgeEdge.Id — pass to DELETE /api/Learning/KnowledgeGraph/Edges/{edgeId}.
 */
export interface KnowledgeEdgeDto {
  id: number;
  sourceNodeId: number;
  targetNodeId: number;
  relationshipType: RelationshipTypeValue;  // 0 Prerequisite | 1 Related
  strength: number;                          // decimal 0.0–1.0
}

/**
 * Full graph DTO returned by GET /api/Learning/KnowledgeGraph/Graph?subjectId=.
 * One call returns all nodes + all edges for the chosen subject tree.
 */
export interface SkillGraphDto {
  subjectId: number;
  nodes: KnowledgeNodeDto[];
  edges: KnowledgeEdgeDto[];
}

/**
 * Item returned by:
 *   GET /api/Learning/KnowledgeGraph/Prerequisites/{nodeId}
 *   GET /api/Learning/KnowledgeGraph/UnlockedBy/{nodeId}
 *
 * These endpoints are [Authorize] (any authenticated user), not AdminOnly.
 * They return a reduced node shape without IsSkillActive.
 */
export interface StudentKnowledgeNodeDto {
  id: number;       // nodeId
  name: string;
  nodeType: NodeTypeValue;
  skillId?: number | null;
}

/** POST body for POST /api/Learning/KnowledgeGraph/Edges (AddKnowledgeEdgeCommand). */
export interface AddKnowledgeEdgeDto {
  sourceNodeId: number;
  targetNodeId: number;
  relationshipType: RelationshipTypeValue;  // always RELATIONSHIP_TYPE.Prerequisite (0) in v1
  strength?: number;                         // hard-coded to 1.0 in v1 (plan D-OQ6)
}

/**
 * Concept picker item from GET /api/learning/Concepts/List.
 *
 * Gap 1 RESOLVED: ConceptDto.cs carries `SubjectId: int` (non-nullable).
 * The FE can filter client-side by concept.subjectId === currentSubjectId
 * to scope the concept picker to the chosen subject tree.
 * The backend ListConceptsQuery also accepts an optional SubjectId filter param.
 */
export interface ConceptListItemDto {
  id: number;
  name: string;
  subjectId: number;  // CONFIRMED present: ConceptDto.SubjectId (int, non-nullable)
}

/**
 * Retained for backwards compatibility (was the only SkillDto before 2c-A).
 * Use SingleSkillResponse for all admin skill list/detail reads.
 * @deprecated Use SingleSkillResponse instead.
 */
export interface SkillDto {
  id: number;
  name: string;
  masteryThreshold: number;
  estimatedTimeMinutes: number;
  conceptId: number;
  isActive: boolean;
}
