// <auto-generated />
using System;
using Learnexia.Modules.Billing.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Learnexia.Modules.Billing.Infrastructure.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    [Migration("20260617155237_AddSeatGraceAndLockState")]
    partial class AddSeatGraceAndLockState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("billing")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Learnexia.Modules.Billing.Domain.Entities.ChildDailyUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChildId")
                        .HasColumnType("integer");

                    b.Property<string>("ChildTimeZoneId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("Africa/Cairo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("DailyUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("DailyUsedDateLocal")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChildId")
                        .IsUnique()
                        .HasDatabaseName("UX_ChildDailyUsages_ChildId");

                    b.ToTable("ChildDailyUsages", "billing", t =>
                        {
                            t.HasCheckConstraint("CK_ChildDailyUsages_DailyUsed_NonNegative", "\"DailyUsed\" >= 0");
                        });
                });

            modelBuilder.Entity("Learnexia.Modules.Billing.Domain.Entities.ChildEnergyAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AllocatedAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("ChildId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CycleEndUtc")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("CycleStartUtc")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<int>("FamilyEnergyAccountId")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("SpentAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ChildId")
                        .HasDatabaseName("IX_ChildEnergyAllocations_ChildId");

                    b.HasIndex("FamilyEnergyAccountId", "ChildId", "CycleStartUtc")
                        .IsUnique()
                        .HasDatabaseName("UX_ChildEnergyAllocations_FamilyChildCycle");

                    b.ToTable("ChildEnergyAllocations", "billing", t =>
                        {
                            t.HasCheckConstraint("CK_ChildEnergyAllocations_AllocatedAmount_NonNegative", "\"AllocatedAmount\" >= 0");

                            t.HasCheckConstraint("CK_ChildEnergyAllocations_SpentAmount_NonNegative", "\"SpentAmount\" >= 0");
                        });
                });

            modelBuilder.Entity("Learnexia.Modules.Billing.Domain.Entities.CreditTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int?>("ChildEnergyAllocationId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("CreditAccountId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("FamilyEnergyAccountId")
                        .HasColumnType("integer");

                    b.Property<int>("FromGranted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("FromPurchased")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<int>("Pool")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ReasonCode")
                        .HasColumnType("integer");

                    b.Property<string>("RelatedActionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RelatedPaymentId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("ResultingGrantedBalance")
                        .HasColumnType("integer");

                    b.Property<int>("ResultingPurchasedBalance")
                        .HasColumnType("integer");

                    b.Property<int?>("SourceBucket")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChildEnergyAllocationId");

                    b.HasIndex("FamilyEnergyAccountId")
                        .HasDatabaseName("IX_CreditTransactions_FamilyEnergyAccountId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_CreditTransactions_IdempotencyKey");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_CreditTransactions_Type");

                    b.HasIndex("CreditAccountId", "OccurredAtUtc")
                        .HasDatabaseName("IX_CreditTransactions_AccountId_OccurredAtUtc");

                    b.ToTable("CreditTransactions", "billing");
                });

            modelBuilder.Entity("Learnexia.Modules.Billing.Domain.Entities.FamilyEnergyAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("ParentUserId")
                        .HasColumnType("integer");

                    b.Property<int>("PurchasedBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("SubscriptionBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("SubscriptionExpiresAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ParentUserId")
                        .IsUnique()
                        .HasDatabaseName("UX_FamilyEnergyAccounts_ParentUserId");

                    b.ToTable("FamilyEnergyAccounts", "billing", t =>
                        {
                            t.HasCheckConstraint("CK_FamilyEnergyAccounts_PurchasedBalance_NonNegative", "\"PurchasedBalance\" >= 0");

                            t.HasCheckConstraint("CK_FamilyEnergyAccounts_SubscriptionBalance_NonNegative", "\"SubscriptionBalance\" >= 0");
                        });
                });

            modelBuilder.Entity("Learnexia.Modules.Billing.Domain.Entities.GlobalSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Key");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_GlobalSettings_UpdatedAt");

                    b.ToTable("GlobalSettings", "platform");
                });

            modelBuilder.Entity("Learnexia.Modules.Billing.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("EGP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("ParentUserId")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderPaymentRef")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("SubscriptionId")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetChildId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_Payments_IdempotencyKey");

                    b.HasIndex("ProviderPaymentRef")
                        .HasDatabaseName("IX_Payments_ProviderPaymentRef");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Payments_Status");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("IX_Payments_SubscriptionId");

                    b.HasIndex("ParentUserId", "Status")
                        .HasDatabaseName("IX_Payments_ParentUserId_Status");

                    b.ToTable("Payments", "billing");
                });

            modelBuilder.Entity("Learnexia.Modules.Billing.Domain.Entities.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<int>("IncludedSeats")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Plans_Code");

                    b.ToTable("Plans", "billing");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 0,
                            IncludedSeats = 1,
                            IsActive = true,
                            Name = "Free"
                        },
                        new
                        {
                            Id = 2,
                            Code = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 0,
                            IncludedSeats = 3,
                            IsActive = true,
                            Name = "Premium"
                        });
                });

            modelBuilder.Entity("Learnexia.Modules.Billing.Domain.Entities.SeatLedgerEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric(18,4)");

                    b.Property<int?>("ChildId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("ParentUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_SeatLedgerEntries_IdempotencyKey")
                        .HasFilter("\"IdempotencyKey\" IS NOT NULL");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("IX_SeatLedgerEntries_OccurredAt");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("IX_SeatLedgerEntries_SubscriptionId");

                    b.HasIndex("SubscriptionId", "ChildId")
                        .HasDatabaseName("IX_SeatLedgerEntries_SubscriptionId_ChildId");

                    b.ToTable("SeatLedgerEntries", "billing");
                });

            modelBuilder.Entity("Learnexia.Modules.Billing.Domain.Entities.SeatReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChildId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("ParentUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("RemovalScheduledAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("SeatState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_SeatReservations_IdempotencyKey")
                        .HasFilter("\"IdempotencyKey\" IS NOT NULL");

                    b.HasIndex("ParentUserId")
                        .HasDatabaseName("IX_SeatReservations_ParentUserId");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("IX_SeatReservations_SubscriptionId");

                    b.HasIndex("SubscriptionId", "ChildId")
                        .IsUnique()
                        .HasDatabaseName("UX_SeatReservations_SubscriptionId_ChildId_Active")
                        .HasFilter("\"Status\" IN (0, 1)");

                    b.ToTable("SeatReservations", "billing");
                });

            modelBuilder.Entity("Learnexia.Modules.Billing.Domain.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BillingPeriod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CurrentCycleEnd")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("CurrentCycleStart")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExtraSeatCancelEffectiveAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("FailedAttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("GraceEndsAt")
                        .HasColumnType("timestamptz");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("ParentUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("PendingBillingPeriod")
                        .HasColumnType("integer");

                    b.Property<int>("PendingExtraSeatRemovals")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("PendingPlanCode")
                        .HasColumnType("integer");

                    b.Property<int>("PlanCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("PurchasedExtraSeats")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("SeatGraceReason")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SeatGraceStartedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Subscriptions_ParentUserId")
                        .HasFilter("\"Status\" = 0");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Subscriptions_Status");

                    b.HasIndex("Status", "NextRetryAt")
                        .HasDatabaseName("IX_Subscriptions_Status_NextRetryAt");

                    b.ToTable("Subscriptions", "billing");
                });

            modelBuilder.Entity("Learnexia.Modules.Billing.Domain.Entities.WebhookEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("Succeeded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventType")
                        .HasDatabaseName("IX_WebhookEvents_EventType");

                    b.HasIndex("ProviderEventId")
                        .IsUnique()
                        .HasDatabaseName("UX_WebhookEvents_ProviderEventId");

                    b.HasIndex("Succeeded")
                        .HasDatabaseName("IX_WebhookEvents_Succeeded");

                    b.ToTable("WebhookEvents", "billing");
                });

            modelBuilder.Entity("Learnexia.Modules.Billing.Domain.Entities.ChildEnergyAllocation", b =>
                {
                    b.HasOne("Learnexia.Modules.Billing.Domain.Entities.FamilyEnergyAccount", "FamilyEnergyAccount")
                        .WithMany("Allocations")
                        .HasForeignKey("FamilyEnergyAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FamilyEnergyAccount");
                });

            modelBuilder.Entity("Learnexia.Modules.Billing.Domain.Entities.CreditTransaction", b =>
                {
                    b.HasOne("Learnexia.Modules.Billing.Domain.Entities.ChildEnergyAllocation", "ChildEnergyAllocation")
                        .WithMany()
                        .HasForeignKey("ChildEnergyAllocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Learnexia.Modules.Billing.Domain.Entities.FamilyEnergyAccount", "FamilyEnergyAccount")
                        .WithMany()
                        .HasForeignKey("FamilyEnergyAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ChildEnergyAllocation");

                    b.Navigation("FamilyEnergyAccount");
                });

            modelBuilder.Entity("Learnexia.Modules.Billing.Domain.Entities.SeatLedgerEntry", b =>
                {
                    b.HasOne("Learnexia.Modules.Billing.Domain.Entities.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Learnexia.Modules.Billing.Domain.Entities.SeatReservation", b =>
                {
                    b.HasOne("Learnexia.Modules.Billing.Domain.Entities.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Learnexia.Modules.Billing.Domain.Entities.FamilyEnergyAccount", b =>
                {
                    b.Navigation("Allocations");
                });
#pragma warning restore 612, 618
        }
    }
}
