// <auto-generated />
using System;
using Learnexia.Modules.Gamification.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Learnexia.Modules.Gamification.Infrastructure.Migrations
{
    [DbContext(typeof(GamificationDbContext))]
    [Migration("20260531075845_AddBadgeDefinitionAndStudentBadge")]
    partial class AddBadgeDefinitionAndStudentBadge
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("gamification")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Learnexia.Modules.Gamification.Domain.Entities.BadgeDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("IconKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.Property<int>("RewardXp")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("Threshold")
                        .HasColumnType("integer");

                    b.Property<int>("TriggerType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_BadgeDefinitions_Code");

                    b.ToTable("BadgeDefinitions", "gamification");
                });

            modelBuilder.Entity("Learnexia.Modules.Gamification.Domain.Entities.HeartLoss", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("HeartsAfter")
                        .HasColumnType("integer");

                    b.Property<int?>("LessonId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OriginEventId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SkillId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentXpProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OriginEventId")
                        .IsUnique()
                        .HasDatabaseName("UX_HeartLosses_OriginEventId");

                    b.HasIndex("StudentXpProfileId")
                        .HasDatabaseName("IX_HeartLosses_StudentXpProfileId");

                    b.ToTable("HeartLosses", "gamification");
                });

            modelBuilder.Entity("Learnexia.Modules.Gamification.Domain.Entities.StudentBadge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AwardedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BadgeDefinitionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<Guid>("OriginEventId")
                        .HasColumnType("uuid");

                    b.Property<string>("OriginEventType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("StudentXpProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BadgeDefinitionId")
                        .HasDatabaseName("IX_StudentBadges_BadgeDefinitionId");

                    b.HasIndex("StudentXpProfileId")
                        .HasDatabaseName("IX_StudentBadges_StudentXpProfileId");

                    b.HasIndex("StudentXpProfileId", "BadgeDefinitionId")
                        .IsUnique()
                        .HasDatabaseName("UX_StudentBadges_StudentXpProfileId_BadgeDefinitionId");

                    b.ToTable("StudentBadges", "gamification");
                });

            modelBuilder.Entity("Learnexia.Modules.Gamification.Domain.Entities.StudentXpProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("CurrentStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<int>("Hearts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5);

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("LastActivityDateUtc")
                        .HasColumnType("date")
                        .HasColumnName("LastActivityDateUtc");

                    b.Property<DateTime>("LastAwardAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastHeartRefillAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LongestStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalXp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique()
                        .HasDatabaseName("UX_StudentXpProfiles_StudentId");

                    b.ToTable("StudentXpProfiles", "gamification");
                });

            modelBuilder.Entity("Learnexia.Modules.Gamification.Domain.Entities.XpAward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("LessonId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OriginEventId")
                        .HasColumnType("uuid");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.Property<int?>("SkillId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentXpProfileId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("XpAmount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudentXpProfileId")
                        .HasDatabaseName("IX_XpAwards_StudentXpProfileId");

                    b.HasIndex("OriginEventId", "Reason")
                        .IsUnique()
                        .HasDatabaseName("UX_XpAwards_OriginEventId_Reason");

                    b.ToTable("XpAwards", "gamification");
                });

            modelBuilder.Entity("Learnexia.Modules.Gamification.Domain.Entities.HeartLoss", b =>
                {
                    b.HasOne("Learnexia.Modules.Gamification.Domain.Entities.StudentXpProfile", "StudentXpProfile")
                        .WithMany()
                        .HasForeignKey("StudentXpProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentXpProfile");
                });

            modelBuilder.Entity("Learnexia.Modules.Gamification.Domain.Entities.StudentBadge", b =>
                {
                    b.HasOne("Learnexia.Modules.Gamification.Domain.Entities.BadgeDefinition", "BadgeDefinition")
                        .WithMany()
                        .HasForeignKey("BadgeDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Learnexia.Modules.Gamification.Domain.Entities.StudentXpProfile", "StudentXpProfile")
                        .WithMany()
                        .HasForeignKey("StudentXpProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BadgeDefinition");

                    b.Navigation("StudentXpProfile");
                });

            modelBuilder.Entity("Learnexia.Modules.Gamification.Domain.Entities.XpAward", b =>
                {
                    b.HasOne("Learnexia.Modules.Gamification.Domain.Entities.StudentXpProfile", "StudentXpProfile")
                        .WithMany("Awards")
                        .HasForeignKey("StudentXpProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentXpProfile");
                });

            modelBuilder.Entity("Learnexia.Modules.Gamification.Domain.Entities.StudentXpProfile", b =>
                {
                    b.Navigation("Awards");
                });
#pragma warning restore 612, 618
        }
    }
}
