// <auto-generated />
using System;
using Learnexia.Modules.Gamification.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Learnexia.Modules.Gamification.Infrastructure.Migrations
{
    [DbContext(typeof(GamificationDbContext))]
    [Migration("20260530174250_AddHeartsColumnsAndHeartLoss")]
    partial class AddHeartsColumnsAndHeartLoss
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("gamification")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Learnexia.Modules.Gamification.Domain.Entities.HeartLoss", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<int>("HeartsAfter")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OriginEventId")
                        .HasColumnType("uuid");

                    b.Property<int>("StudentXpProfileId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OriginEventId")
                        .IsUnique()
                        .HasDatabaseName("UX_HeartLosses_OriginEventId");

                    b.HasIndex("StudentXpProfileId")
                        .HasDatabaseName("IX_HeartLosses_StudentXpProfileId");

                    b.ToTable("HeartLosses", "gamification");
                });

            modelBuilder.Entity("Learnexia.Modules.Gamification.Domain.Entities.StudentXpProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("CurrentStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<int>("Hearts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5);

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("LastActivityDateUtc")
                        .HasColumnType("date")
                        .HasColumnName("LastActivityDateUtc");

                    b.Property<DateTime>("LastAwardAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastHeartRefillAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LongestStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalXp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique()
                        .HasDatabaseName("UX_StudentXpProfiles_StudentId");

                    b.ToTable("StudentXpProfiles", "gamification");
                });

            modelBuilder.Entity("Learnexia.Modules.Gamification.Domain.Entities.XpAward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("LessonId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OriginEventId")
                        .HasColumnType("uuid");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.Property<int?>("SkillId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentXpProfileId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("XpAmount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudentXpProfileId")
                        .HasDatabaseName("IX_XpAwards_StudentXpProfileId");

                    b.HasIndex("OriginEventId", "Reason")
                        .IsUnique()
                        .HasDatabaseName("UX_XpAwards_OriginEventId_Reason");

                    b.ToTable("XpAwards", "gamification");
                });

            modelBuilder.Entity("Learnexia.Modules.Gamification.Domain.Entities.HeartLoss", b =>
                {
                    b.HasOne("Learnexia.Modules.Gamification.Domain.Entities.StudentXpProfile", "StudentXpProfile")
                        .WithMany()
                        .HasForeignKey("StudentXpProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentXpProfile");
                });

            modelBuilder.Entity("Learnexia.Modules.Gamification.Domain.Entities.XpAward", b =>
                {
                    b.HasOne("Learnexia.Modules.Gamification.Domain.Entities.StudentXpProfile", "StudentXpProfile")
                        .WithMany("Awards")
                        .HasForeignKey("StudentXpProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentXpProfile");
                });

            modelBuilder.Entity("Learnexia.Modules.Gamification.Domain.Entities.StudentXpProfile", b =>
                {
                    b.Navigation("Awards");
                });
#pragma warning restore 612, 618
        }
    }
}
